import json

CATALOG = 'Memonta/Resources/Localizable.xcstrings'

LANGS = ['zh-Hant', 'en', 'ja', 'ko', 'fr', 'de', 'es', 'it', 'pt', 'ru',
         'ar', 'hi', 'th', 'vi', 'id', 'tr', 'nl', 'pl', 'uk', 'sv']

T = {}


def add(key, vals):
    assert len(vals) == 20, key
    T[key] = vals


add(
    "保存到本地数据库时出错（常见原因是磁盘已写满）。当前界面上的改动可能在重启后丢失，请检查磁盘剩余空间后重试；本次运行的详细原因已记入应用日志（category: Persistence）。",
    [
        "儲存到本機資料庫時發生錯誤（常見原因是磁碟已寫滿）。目前介面上的變更可能在重新啟動後遺失，請檢查磁碟剩餘空間後重試；本次執行的詳細原因已記入應用程式日誌（category: Persistence）。",
        "An error occurred while saving to the local database (a common cause is a full disk). Changes on the current screen may be lost after restart; check the free disk space and try again. The detailed reason for this session has been recorded in the app log (category: Persistence).",
        "ローカルデータベースへの保存中にエラーが発生しました（よくある原因はディスクの容量不足です）。現在の画面での変更は再起動後に失われる可能性があります。ディスクの空き容量を確認して再試行してください。今回の詳細な原因はアプリログに記録されています（category: Persistence）。",
        "로컬 데이터베이스에 저장하는 중 오류가 발생했습니다(흔한 원인은 디스크가 가득 찬 경우입니다). 현재 화면의 변경 사항은 재시작 후 사라질 수 있으니 디스크 여유 공간을 확인한 후 다시 시도하세요. 이번 실행의 자세한 원인은 앱 로그에 기록되었습니다(category: Persistence).",
        "Une erreur s'est produite lors de l'enregistrement dans la base de données locale (une cause fréquente est un disque plein). Les modifications apportées à l'écran actuel peuvent être perdues après un redémarrage ; vérifiez l'espace disque disponible et réessayez. La raison détaillée de cette session a été consignée dans le journal de l'application (category: Persistence).",
        "Beim Speichern in der lokalen Datenbank ist ein Fehler aufgetreten (häufige Ursache ist eine volle Festplatte). Änderungen auf dem aktuellen Bildschirm können nach einem Neustart verloren gehen; prüfe den freien Speicherplatz und versuche es erneut. Der genaue Grund für diesen Lauf wurde im App-Log festgehalten (category: Persistence).",
        "Se produjo un error al guardar en la base de datos local (una causa habitual es que el disco esté lleno). Los cambios de la pantalla actual pueden perderse tras reiniciar; comprueba el espacio libre en disco y vuelve a intentarlo. El motivo detallado de esta sesión se ha registrado en el registro de la app (category: Persistence).",
        "Si è verificato un errore durante il salvataggio nel database locale (una causa comune è il disco pieno). Le modifiche nella schermata corrente potrebbero andare perse dopo il riavvio; controlla lo spazio libero su disco e riprova. Il motivo dettagliato di questa sessione è stato registrato nel log dell'app (category: Persistence).",
        "Ocorreu um erro ao salvar no banco de dados local (uma causa comum é o disco cheio). As alterações na tela atual podem ser perdidas após reiniciar; verifique o espaço livre em disco e tente novamente. O motivo detalhado desta sessão foi registrado no log do app (category: Persistence).",
        "При сохранении в локальную базу данных произошла ошибка (частая причина — заполненный диск). Изменения на текущем экране могут быть потеряны после перезапуска; проверьте свободное место на диске и повторите попытку. Подробная причина этого сеанса записана в журнал приложения (category: Persistence).",
        "حدث خطأ أثناء الحفظ في قاعدة البيانات المحلية (ومن الأسباب الشائعة امتلاء القرص). قد تُفقد التغييرات على الشاشة الحالية بعد إعادة التشغيل، لذا تحقق من المساحة الحرة على القرص وأعد المحاولة. سُجّل السبب التفصيلي لهذه الجلسة في سجل التطبيق (category: Persistence).",
        "स्थानीय डेटाबेस में सहेजते समय त्रुटि हुई (एक सामान्य कारण डिस्क भरा होना है)। मौजूदा स्क्रीन के बदलाव पुनः आरंभ के बाद खो सकते हैं; डिस्क में उपलब्ध जगह जाँचें और दोबारा प्रयास करें। इस सत्र का विस्तृत कारण ऐप लॉग में दर्ज कर लिया गया है (category: Persistence)।",
        "เกิดข้อผิดพลาดขณะบันทึกลงฐานข้อมูลในเครื่อง (สาเหตุที่พบบ่อยคือดิสก์เต็ม) การเปลี่ยนแปลงบนหน้าจอปัจจุบันอาจสูญหายหลังรีสตาร์ท โปรดตรวจสอบพื้นที่ว่างบนดิสก์แล้วลองใหม่ สาเหตุโดยละเอียดของครั้งนี้ถูกบันทึกไว้ในบันทึกของแอป (category: Persistence)",
        "Đã xảy ra lỗi khi lưu vào cơ sở dữ liệu cục bộ (nguyên nhân phổ biến là đĩa đã đầy). Các thay đổi trên màn hình hiện tại có thể mất sau khi khởi động lại; hãy kiểm tra dung lượng trống trên đĩa rồi thử lại. Nguyên nhân chi tiết của lần chạy này đã được ghi vào nhật ký ứng dụng (category: Persistence).",
        "Terjadi kesalahan saat menyimpan ke basis data lokal (penyebab umum adalah disk penuh). Perubahan pada layar saat ini dapat hilang setelah mulai ulang; periksa ruang disk yang tersedia lalu coba lagi. Penyebab rinci untuk sesi ini telah dicatat di log aplikasi (category: Persistence).",
        "Yerel veritabanına kaydederken bir hata oluştu (yaygın neden disk dolu olmasıdır). Geçerli ekrandaki değişiklikler yeniden başlatmadan sonra kaybolabilir; disk alanını kontrol edip tekrar deneyin. Bu oturumun ayrıntılı nedeni uygulama günlüğüne kaydedildi (category: Persistence).",
        "Er is een fout opgetreden bij het opslaan in de lokale database (een veelvoorkomende oorzaak is een volle schijf). Wijzigingen op het huidige scherm kunnen na een herstart verloren gaan; controleer de vrije schijfruimte en probeer het opnieuw. De gedetailleerde oorzaak van deze sessie is vastgelegd in het app-logboek (category: Persistence).",
        "Wystąpił błąd podczas zapisywania w lokalnej bazie danych (częstą przyczyną jest zapełniony dysk). Zmiany na bieżącym ekranie mogą zniknąć po ponownym uruchomieniu; sprawdź wolne miejsce na dysku i spróbuj ponownie. Szczegółowa przyczyna tej sesji została zapisana w dzienniku aplikacji (category: Persistence).",
        "Під час збереження до локальної бази даних сталася помилка (часта причина — заповнений диск). Зміни на поточному екрані можуть бути втрачені після перезапуску; перевірте вільне місце на диску й повторіть спробу. Детальну причину цього сеансу записано в журнал застосунку (category: Persistence).",
        "Ett fel uppstod när data skulle sparas i den lokala databasen (en vanlig orsak är full disk). Ändringar på den aktuella skärmen kan gå förlorade efter omstart; kontrollera ledigt diskutrymme och försök igen. Den detaljerade orsaken för denna körning har registrerats i apploggen (category: Persistence).",
    ],
)

add(
    "拖拽音频文件到窗口，或点击工具栏的导入按钮。支持 m4a、mp3、wav，也支持 mp4、mov、m4v 视频（自动抽取音轨，原始视频同文件夹保留）。导入文件同样存储到 Memonta 文件夹。",
    [
        "拖曳音訊檔案到視窗，或點擊工具列的匯入按鈕。支援 m4a、mp3、wav，也支援 mp4、mov、m4v 影片（自動擷取音軌，原始影片同資料夾保留）。匯入檔案同樣儲存到 Memonta 資料夾。",
        "Drag an audio file into the window, or click the import button in the toolbar. Supports m4a, mp3, and wav, as well as mp4, mov, and m4v video (audio track extracted automatically; the original video is kept in the same folder). Imported files are also stored in the Memonta folder.",
        "音声ファイルをウィンドウにドラッグするか、ツールバーの読み込みボタンをクリックします。m4a、mp3、wav に対応し、mp4、mov、m4v 動画にも対応します（音声トラックを自動抽出し、元の動画は同じフォルダに保持されます）。読み込んだファイルも Memonta フォルダに保存されます。",
        "오디오 파일을 창으로 끌어다 놓거나 도구 모음의 가져오기 버튼을 클릭하세요. m4a, mp3, wav를 지원하며 mp4, mov, m4v 동영상도 지원합니다(오디오 트랙을 자동 추출하고 원본 동영상은 같은 폴더에 보관됩니다). 가져온 파일도 Memonta 폴더에 저장됩니다.",
        "Faites glisser un fichier audio dans la fenêtre ou cliquez sur le bouton d'import de la barre d'outils. Prend en charge m4a, mp3 et wav, ainsi que les vidéos mp4, mov et m4v (la piste audio est extraite automatiquement et la vidéo d'origine est conservée dans le même dossier). Les fichiers importés sont également stockés dans le dossier Memonta.",
        "Ziehe eine Audiodatei in das Fenster oder klicke auf die Import-Schaltfläche in der Symbolleiste. Unterstützt m4a, mp3 und wav sowie mp4-, mov- und m4v-Videos (Audiospur wird automatisch extrahiert, das Originalvideo bleibt im selben Ordner erhalten). Importierte Dateien werden ebenfalls im Memonta-Ordner gespeichert.",
        "Arrastra un archivo de audio a la ventana o haz clic en el botón de importar de la barra de herramientas. Compatible con m4a, mp3 y wav, y también con vídeos mp4, mov y m4v (la pista de audio se extrae automáticamente y el vídeo original se conserva en la misma carpeta). Los archivos importados también se guardan en la carpeta Memonta.",
        "Trascina un file audio nella finestra oppure fai clic sul pulsante di importazione nella barra degli strumenti. Supporta m4a, mp3 e wav, oltre ai video mp4, mov e m4v (la traccia audio viene estratta automaticamente e il video originale viene conservato nella stessa cartella). Anche i file importati vengono salvati nella cartella Memonta.",
        "Arraste um arquivo de áudio para a janela ou clique no botão de importar da barra de ferramentas. Suporta m4a, mp3 e wav, além de vídeos mp4, mov e m4v (a faixa de áudio é extraída automaticamente e o vídeo original é mantido na mesma pasta). Os arquivos importados também são salvos na pasta Memonta.",
        "Перетащите аудиофайл в окно или нажмите кнопку импорта на панели инструментов. Поддерживаются m4a, mp3 и wav, а также видео mp4, mov и m4v (звуковая дорожка извлекается автоматически, исходное видео сохраняется в той же папке). Импортированные файлы также сохраняются в папке Memonta.",
        "اسحب ملفًا صوتيًا إلى النافذة أو انقر زر الاستيراد في شريط الأدوات. يدعم m4a وmp3 وwav، وكذلك فيديو mp4 وmov وm4v (يُستخرج المسار الصوتي تلقائيًا ويُحتفظ بالفيديو الأصلي في المجلد نفسه). تُحفظ الملفات المستوردة أيضًا في مجلد Memonta.",
        "ऑडियो फ़ाइल को विंडो में खींचें, या टूलबार के आयात बटन पर क्लिक करें। m4a, mp3 और wav के साथ-साथ mp4, mov और m4v वीडियो का समर्थन करता है (ऑडियो ट्रैक स्वतः निकाला जाता है, मूल वीडियो उसी फ़ोल्डर में सुरक्षित रहता है)। आयातित फ़ाइलें भी Memonta फ़ोल्डर में सहेजी जाती हैं।",
        "ลากไฟล์เสียงไปยังหน้าต่าง หรือคลิกปุ่มนำเข้าบนแถบเครื่องมือ รองรับ m4a, mp3 และ wav รวมถึงวิดีโอ mp4, mov และ m4v (ดึงแทร็กเสียงออกโดยอัตโนมัติ และเก็บวิดีโอต้นฉบับไว้ในโฟลเดอร์เดียวกัน) ไฟล์ที่นำเข้าก็จะถูกบันทึกไว้ในโฟลเดอร์ Memonta เช่นกัน",
        "Kéo tệp âm thanh vào cửa sổ, hoặc nhấp vào nút nhập trên thanh công cụ. Hỗ trợ m4a, mp3 và wav, cũng như video mp4, mov và m4v (tự động trích xuất âm thanh, video gốc được giữ trong cùng thư mục). Tệp đã nhập cũng được lưu vào thư mục Memonta.",
        "Seret file audio ke jendela, atau klik tombol impor di bilah alat. Mendukung m4a, mp3, dan wav, serta video mp4, mov, dan m4v (trek audio diekstrak otomatis, video asli disimpan di folder yang sama). File yang diimpor juga disimpan di folder Memonta.",
        "Bir ses dosyasını pencereye sürükleyin veya araç çubuğundaki içe aktar düğmesine tıklayın. m4a, mp3 ve wav ile birlikte mp4, mov ve m4v videoyu destekler (ses kanalı otomatik çıkarılır, orijinal video aynı klasörde saklanır). İçe aktarılan dosyalar da Memonta klasörüne kaydedilir.",
        "Sleep een audiobestand naar het venster of klik op de importknop in de werkbalk. Ondersteunt m4a, mp3 en wav, evenals mp4-, mov- en m4v-video's (audiospoor wordt automatisch geëxtraheerd, de originele video blijft in dezelfde map bewaard). Geïmporteerde bestanden worden ook in de Memonta-map opgeslagen.",
        "Przeciągnij plik audio do okna lub kliknij przycisk importu na pasku narzędzi. Obsługuje m4a, mp3 i wav oraz wideo mp4, mov i m4v (ścieżka audio jest wyodrębniana automatycznie, oryginalne wideo pozostaje w tym samym folderze). Zaimportowane pliki są również zapisywane w folderze Memonta.",
        "Перетягніть аудіофайл у вікно або натисніть кнопку імпорту на панелі інструментів. Підтримує m4a, mp3 і wav, а також відео mp4, mov і m4v (звукову доріжку вилучено автоматично, оригінальне відео зберігається в тій самій теці). Імпортовані файли також зберігаються в теці Memonta.",
        "Dra ett ljudklipp till fönstret eller klicka på importknappen i verktygsfältet. Stöder m4a, mp3 och wav samt mp4-, mov- och m4v-video (ljudspåret extraheras automatiskt och originalvideon sparas i samma mapp). Importerade filer sparas också i Memonta-mappen.",
    ],
)

add(
    "部分加密内容无法解密，加密密钥可能已更改或 Keychain 中的密钥被删除。对应内容将显示为空，但原始数据仍保留在磁盘与数据库中。请勿删除 Keychain 中的密钥，否则已加密的数据将无法恢复。",
    [
        "部分加密內容無法解密，加密金鑰可能已變更或 Keychain 中的金鑰被刪除。對應內容將顯示為空，但原始資料仍保留在磁碟與資料庫中。請勿刪除 Keychain 中的金鑰，否則已加密的資料將無法復原。",
        "Some encrypted content cannot be decrypted; the encryption key may have changed or the key in the Keychain may have been deleted. The corresponding content will appear empty, but the raw data remains on disk and in the database. Do not delete the key in the Keychain, or the encrypted data will be unrecoverable.",
        "一部の暗号化されたコンテンツを復号できません。暗号化キーが変更されたか、Keychain 内のキーが削除された可能性があります。該当するコンテンツは空で表示されますが、元のデータはディスクとデータベースに残っています。Keychain 内のキーを削除しないでください。削除すると暗号化されたデータを復元できなくなります。",
        "일부 암호화된 콘텐츠를 복호화할 수 없습니다. 암호화 키가 변경되었거나 Keychain의 키가 삭제되었을 수 있습니다. 해당 콘텐츠는 비어 있게 표시되지만 원본 데이터는 디스크와 데이터베이스에 남아 있습니다. Keychain의 키를 삭제하지 마세요. 삭제하면 암호화된 데이터를 복구할 수 없습니다.",
        "Certains contenus chiffrés ne peuvent pas être déchiffrés ; la clé de chiffrement a peut-être changé ou la clé du trousseau a été supprimée. Les contenus concernés apparaîtront vides, mais les données brutes restent sur le disque et dans la base de données. Ne supprimez pas la clé du trousseau, sinon les données chiffrées seront irrécupérables.",
        "Ein Teil der verschlüsselten Inhalte kann nicht entschlüsselt werden; möglicherweise wurde der Verschlüsselungsschlüssel geändert oder der Schlüssel im Keychain gelöscht. Die betreffenden Inhalte erscheinen leer, die Rohdaten bleiben jedoch auf dem Datenträger und in der Datenbank erhalten. Lösche den Schlüssel im Keychain nicht, sonst sind die verschlüsselten Daten nicht mehr wiederherstellbar.",
        "Parte del contenido cifrado no se puede descifrar; puede que la clave de cifrado haya cambiado o que se haya eliminado la clave del Llavero. El contenido correspondiente aparecerá vacío, pero los datos originales permanecen en el disco y en la base de datos. No elimines la clave del Llavero, o los datos cifrados no se podrán recuperar.",
        "Parte dei contenuti cifrati non può essere decifrata; la chiave di cifratura potrebbe essere cambiata o la chiave nel Portachiavi potrebbe essere stata eliminata. I contenuti corrispondenti appariranno vuoti, ma i dati originali restano sul disco e nel database. Non eliminare la chiave dal Portachiavi, altrimenti i dati cifrati non potranno essere recuperati.",
        "Parte do conteúdo criptografado não pode ser descriptografada; a chave de criptografia pode ter mudado ou a chave no Keychain pode ter sido excluída. O conteúdo correspondente aparecerá vazio, mas os dados originais permanecem no disco e no banco de dados. Não exclua a chave no Keychain, ou os dados criptografados não poderão ser recuperados.",
        "Часть зашифрованного содержимого не удаётся расшифровать; возможно, ключ шифрования изменился или ключ в Keychain был удалён. Соответствующее содержимое будет отображаться пустым, но исходные данные остаются на диске и в базе данных. Не удаляйте ключ в Keychain, иначе зашифрованные данные нельзя будет восстановить.",
        "لا يمكن فك تشفير بعض المحتوى المشفَّر؛ ربما تغيّر مفتاح التشفير أو حُذف المفتاح من سلسلة المفاتيح. سيظهر المحتوى المقابل فارغًا، لكن البيانات الأصلية لا تزال محفوظة على القرص وفي قاعدة البيانات. لا تحذف المفتاح من سلسلة المفاتيح، وإلا فلن يمكن استعادة البيانات المشفَّرة.",
        "कुछ एन्क्रिप्टेड सामग्री को डिक्रिप्ट नहीं किया जा सकता; एन्क्रिप्शन कुंजी बदल गई हो सकती है या Keychain में कुंजी हटा दी गई हो सकती है। संबंधित सामग्री खाली दिखाई देगी, लेकिन मूल डेटा डिस्क और डेटाबेस में सुरक्षित रहता है। Keychain में कुंजी न हटाएँ, अन्यथा एन्क्रिप्टेड डेटा पुनर्प्राप्त नहीं किया जा सकेगा।",
        "เนื้อหาที่เข้ารหัสบางส่วนไม่สามารถถอดรหัสได้ อาจเป็นเพราะคีย์เข้ารหัสเปลี่ยนไปหรือคีย์ใน Keychain ถูกลบ เนื้อหาที่เกี่ยวข้องจะแสดงเป็นค่าว่าง แต่ข้อมูลต้นฉบับยังคงอยู่บนดิสก์และในฐานข้อมูล อย่าลบคีย์ใน Keychain มิฉะนั้นข้อมูลที่เข้ารหัสจะกู้คืนไม่ได้",
        "Một phần nội dung đã mã hóa không thể giải mã; có thể khóa mã hóa đã thay đổi hoặc khóa trong Keychain đã bị xóa. Nội dung tương ứng sẽ hiển thị trống, nhưng dữ liệu gốc vẫn còn trên đĩa và trong cơ sở dữ liệu. Đừng xóa khóa trong Keychain, nếu không dữ liệu đã mã hóa sẽ không thể khôi phục.",
        "Sebagian konten terenkripsi tidak dapat didekripsi; kunci enkripsi mungkin telah berubah atau kunci di Keychain telah dihapus. Konten terkait akan tampil kosong, tetapi data asli tetap ada di disk dan basis data. Jangan hapus kunci di Keychain, jika tidak data terenkripsi tidak dapat dipulihkan.",
        "Bazı şifrelenmiş içeriklerin şifresi çözülemiyor; şifreleme anahtarı değişmiş veya Keychain'deki anahtar silinmiş olabilir. İlgili içerik boş görünecek, ancak ham veriler diskte ve veritabanında kalır. Keychain'deki anahtarı silmeyin, aksi halde şifrelenmiş veriler kurtarılamaz.",
        "Een deel van de versleutelde inhoud kan niet worden ontsleuteld; mogelijk is de versleutelingssleutel gewijzigd of is de sleutel in de Keychain verwijderd. De betreffende inhoud wordt leeg weergegeven, maar de ruwe gegevens blijven op de schijf en in de database staan. Verwijder de sleutel in de Keychain niet, anders kunnen de versleutelde gegevens niet worden hersteld.",
        "Części zaszyfrowanej treści nie można odszyfrować; klucz szyfrowania mógł się zmienić lub klucz w Keychain został usunięty. Odpowiednia treść będzie wyświetlana jako pusta, ale oryginalne dane pozostają na dysku i w bazie danych. Nie usuwaj klucza w Keychain, w przeciwnym razie zaszyfrowanych danych nie będzie można odzyskać.",
        "Частину зашифрованого вмісту не вдається розшифрувати; можливо, ключ шифрування змінився або ключ у Keychain було видалено. Відповідний вміст відображатиметься порожнім, але вихідні дані залишаються на диску й у базі даних. Не видаляйте ключ у Keychain, інакше зашифровані дані неможливо буде відновити.",
        "En del krypterat innehåll kan inte dekrypteras; krypteringsnyckeln kan ha ändrats eller så har nyckeln i Keychain tagits bort. Motsvarande innehåll visas tomt, men rådata finns kvar på disken och i databasen. Ta inte bort nyckeln i Keychain, annars kan de krypterade uppgifterna inte återställas.",
    ],
)

add(
    "Memonta 收集以下数据用于提供录音、转写和总结功能：\n• 音频文件（您导入的录音或本机录制的会议音频）\n• 转写文本（由音频生成）\n• 总结（由 LLM 生成）\n\n所有数据仅存储在您的设备本地，不会上传到我们的服务器。",
    [
        "Memonta 收集以下資料用於提供錄音、轉寫和總結功能：\n• 音訊檔案（您匯入的錄音或本機錄製的會議音訊）\n• 轉寫文字（由音訊產生）\n• 總結（由 LLM 產生）\n\n所有資料僅儲存在您的裝置本機，不會上傳到我們的伺服器。",
        "Memonta collects the following data to provide recording, transcription, and summarization features:\n• Audio files (recordings you import or meeting audio recorded on this device)\n• Transcript text (generated from audio)\n• Summaries (generated by the LLM)\n\nAll data is stored only locally on your device and is never uploaded to our servers.",
        "Memonta は、録音・文字起こし・要約機能を提供するために以下のデータを収集します：\n• 音声ファイル（読み込んだ録音、または本機で録音した会議音声）\n• 文字起こしテキスト（音声から生成）\n• 要約（LLM が生成）\n\nすべてのデータはお使いのデバイス上にのみ保存され、当社のサーバーにアップロードされることはありません。",
        "Memonta는 녹음, 전사 및 요약 기능을 제공하기 위해 다음 데이터를 수집합니다:\n• 오디오 파일(가져온 녹음 또는 이 기기에서 녹음한 회의 오디오)\n• 전사 텍스트(오디오에서 생성)\n• 요약(LLM이 생성)\n\n모든 데이터는 사용자 기기에만 로컬로 저장되며 당사 서버로 업로드되지 않습니다.",
        "Memonta collecte les données suivantes pour fournir les fonctions d'enregistrement, de transcription et de résumé :\n• Fichiers audio (enregistrements que vous importez ou audio de réunion enregistré sur cet appareil)\n• Texte de transcription (généré à partir de l'audio)\n• Résumés (générés par le LLM)\n\nToutes les données sont stockées uniquement en local sur votre appareil et ne sont jamais envoyées à nos serveurs.",
        "Memonta erhebt die folgenden Daten, um Funktionen für Aufnahme, Transkription und Zusammenfassung bereitzustellen:\n• Audiodateien (von dir importierte Aufnahmen oder auf diesem Gerät aufgenommenes Besprechungsaudio)\n• Transkripttext (aus Audio erzeugt)\n• Zusammenfassungen (vom LLM erzeugt)\n\nAlle Daten werden nur lokal auf deinem Gerät gespeichert und nie auf unsere Server hochgeladen.",
        "Memonta recopila los siguientes datos para ofrecer las funciones de grabación, transcripción y resumen:\n• Archivos de audio (grabaciones que importas o audio de reunión grabado en este dispositivo)\n• Texto de transcripción (generado a partir del audio)\n• Resúmenes (generados por el LLM)\n\nTodos los datos se almacenan solo localmente en tu dispositivo y nunca se suben a nuestros servidores.",
        "Memonta raccoglie i seguenti dati per offrire le funzioni di registrazione, trascrizione e riepilogo:\n• File audio (registrazioni che importi o audio di riunione registrato su questo dispositivo)\n• Testo della trascrizione (generato dall'audio)\n• Riepiloghi (generati dal LLM)\n\nTutti i dati sono memorizzati solo localmente sul tuo dispositivo e non vengono mai caricati sui nostri server.",
        "O Memonta coleta os seguintes dados para oferecer os recursos de gravação, transcrição e resumo:\n• Arquivos de áudio (gravações que você importa ou áudio de reunião gravado neste dispositivo)\n• Texto da transcrição (gerado a partir do áudio)\n• Resumos (gerados pelo LLM)\n\nTodos os dados são armazenados apenas localmente no seu dispositivo e nunca são enviados aos nossos servidores.",
        "Memonta собирает следующие данные для работы функций записи, расшифровки и составления сводок:\n• Аудиофайлы (импортированные вами записи или аудио встреч, записанное на этом устройстве)\n• Текст расшифровки (создаётся из аудио)\n• Сводки (создаются LLM)\n\nВсе данные хранятся только локально на вашем устройстве и никогда не загружаются на наши серверы.",
        "يجمع Memonta البيانات التالية لتوفير ميزات التسجيل والنسخ النصي والتلخيص:\n• ملفات صوتية (التسجيلات التي تستوردها أو صوت الاجتماع المسجّل على هذا الجهاز)\n• نص النسخ (يُولّد من الصوت)\n• الملخصات (تُولّدها LLM)\n\nتُخزَّن جميع البيانات محليًا على جهازك فقط ولا تُرفع أبدًا إلى خوادمنا.",
        "Memonta रिकॉर्डिंग, ट्रांसक्रिप्शन और सारांश सुविधाएँ देने के लिए निम्नलिखित डेटा एकत्र करता है:\n• ऑडियो फ़ाइलें (आपके द्वारा आयात की गई रिकॉर्डिंग या इस डिवाइस पर रिकॉर्ड किया गया मीटिंग ऑडियो)\n• ट्रांसक्रिप्ट टेक्स्ट (ऑडियो से बनाया गया)\n• सारांश (LLM द्वारा बनाए गए)\n\nसारा डेटा केवल आपके डिवाइस पर स्थानीय रूप से संग्रहीत होता है और कभी हमारे सर्वर पर अपलोड नहीं किया जाता।",
        "Memonta เก็บรวบรวมข้อมูลต่อไปนี้เพื่อให้บริการฟีเจอร์บันทึกเสียง ถอดเสียง และสรุป:\n• ไฟล์เสียง (การบันทึกที่คุณนำเข้าหรือเสียงประชุมที่บันทึกบนอุปกรณ์นี้)\n• ข้อความถอดเสียง (สร้างจากไฟล์เสียง)\n• สรุป (สร้างโดย LLM)\n\nข้อมูลทั้งหมดถูกจัดเก็บไว้ในเครื่องของคุณเท่านั้น และจะไม่ถูกอัปโหลดไปยังเซิร์ฟเวอร์ของเรา",
        "Memonta thu thập dữ liệu sau để cung cấp các tính năng ghi âm, gỡ băng và tóm tắt:\n• Tệp âm thanh (bản ghi bạn nhập hoặc âm thanh cuộc họp được ghi trên thiết bị này)\n• Văn bản gỡ băng (được tạo từ âm thanh)\n• Bản tóm tắt (do LLM tạo)\n\nMọi dữ liệu chỉ được lưu cục bộ trên thiết bị của bạn và không bao giờ được tải lên máy chủ của chúng tôi.",
        "Memonta mengumpulkan data berikut untuk menyediakan fitur perekaman, transkripsi, dan ringkasan:\n• File audio (rekaman yang Anda impor atau audio rapat yang direkam di perangkat ini)\n• Teks transkrip (dihasilkan dari audio)\n• Ringkasan (dihasilkan oleh LLM)\n\nSemua data hanya disimpan secara lokal di perangkat Anda dan tidak pernah diunggah ke server kami.",
        "Memonta, kayıt, döküm ve özetleme özelliklerini sunmak için aşağıdaki verileri toplar:\n• Ses dosyaları (içe aktardığınız kayıtlar veya bu cihazda kaydedilen toplantı sesi)\n• Döküm metni (sesten oluşturulur)\n• Özetler (LLM tarafından oluşturulur)\n\nTüm veriler yalnızca cihazınızda yerel olarak saklanır ve sunucularımıza asla yüklenmez.",
        "Memonta verzamelt de volgende gegevens om functies voor opnemen, transcriberen en samenvatten te bieden:\n• Audiobestanden (opnamen die je importeert of vergaderaudio die op dit apparaat is opgenomen)\n• Transcriptietekst (gegenereerd uit audio)\n• Samenvattingen (gegenereerd door de LLM)\n\nAlle gegevens worden alleen lokaal op je apparaat opgeslagen en nooit naar onze servers geüpload.",
        "Memonta zbiera następujące dane, aby zapewnić funkcje nagrywania, transkrypcji i podsumowywania:\n• Pliki audio (importowane nagrania lub dźwięk spotkania nagrany na tym urządzeniu)\n• Tekst transkrypcji (generowany z dźwięku)\n• Podsumowania (generowane przez LLM)\n\nWszystkie dane są przechowywane wyłącznie lokalnie na Twoim urządzeniu i nigdy nie są przesyłane na nasze serwery.",
        "Memonta збирає такі дані для роботи функцій запису, розшифровки та підсумків:\n• Аудіофайли (записи, які ви імпортуєте, або аудіо зустрічі, записане на цьому пристрої)\n• Текст розшифровки (створюється з аудіо)\n• Підсумки (створюються LLM)\n\nУсі дані зберігаються лише локально на вашому пристрої й ніколи не завантажуються на наші сервери.",
        "Memonta samlar in följande data för att tillhandahålla funktionerna inspelning, transkription och sammanfattning:\n• Ljudfiler (inspelningar du importerar eller mötesljud som spelats in på den här enheten)\n• Transkriptionstext (genereras från ljud)\n• Sammanfattningar (genereras av LLM)\n\nAll data lagras endast lokalt på din enhet och laddas aldrig upp till våra servrar.",
    ],
)

add(
    "• 录音文件、转写记录和总结统一存储在用户文稿目录下的 Memonta 文件夹（~/Documents/Memonta/），按年月日时分归档到子文件夹\n• 转写文本和总结同时在本地数据库加密存储\n• API Key 使用 macOS Keychain / iOS Keychain 安全存储\n• 应用卸载后所有数据将被清除（文稿目录下的音频文件除外，需手动删除）",
    [
        "• 錄音檔案、轉寫記錄和總結統一儲存在使用者文稿目錄下的 Memonta 資料夾（~/Documents/Memonta/），按年月日時分歸檔到子資料夾\n• 轉寫文字和總結同時在本機資料庫加密儲存\n• API Key 使用 macOS Keychain / iOS Keychain 安全儲存\n• 應用程式解除安裝後所有資料將被清除（文稿目錄下的音訊檔案除外，需手動刪除）",
        "• Recording files, transcripts, and summaries are stored together in the Memonta folder under your Documents directory (~/Documents/Memonta/), archived into subfolders by year, month, day, hour, and minute\n• Transcript text and summaries are also stored encrypted in the local database\n• API keys are stored securely using macOS Keychain / iOS Keychain\n• Uninstalling the app erases all data (except audio files in the Documents folder, which must be deleted manually)",
        "• 録音ファイル、文字起こし記録、要約は、ユーザーの書類ディレクトリ内の Memonta フォルダ（~/Documents/Memonta/）にまとめて保存され、年月日時分ごとにサブフォルダへアーカイブされます\n• 文字起こしテキストと要約はローカルデータベースにも暗号化して保存されます\n• API Key は macOS Keychain / iOS Keychain で安全に保存されます\n• アプリをアンインストールするとすべてのデータが消去されます（書類ディレクトリ内の音声ファイルを除く。これらは手動で削除する必要があります）",
        "• 녹음 파일, 전사 기록 및 요약은 사용자 문서 디렉터리의 Memonta 폴더(~/Documents/Memonta/)에 함께 저장되며 연월일시분별 하위 폴더로 보관됩니다\n• 전사 텍스트와 요약은 로컬 데이터베이스에도 암호화되어 저장됩니다\n• API Key는 macOS Keychain / iOS Keychain에 안전하게 저장됩니다\n• 앱을 제거하면 모든 데이터가 삭제됩니다(문서 디렉터리의 오디오 파일은 제외되며 수동으로 삭제해야 합니다)",
        "• Les fichiers d'enregistrement, les transcriptions et les résumés sont stockés ensemble dans le dossier Memonta de votre répertoire Documents (~/Documents/Memonta/), archivés dans des sous-dossiers par année, mois, jour, heure et minute\n• Le texte de transcription et les résumés sont également stockés de façon chiffrée dans la base de données locale\n• Les clés API sont stockées en toute sécurité via le trousseau macOS / iOS\n• La désinstallation de l'application efface toutes les données (sauf les fichiers audio du dossier Documents, à supprimer manuellement)",
        "• Aufnahmedateien, Transkripte und Zusammenfassungen werden gemeinsam im Memonta-Ordner unter deinem Dokumente-Verzeichnis (~/Documents/Memonta/) gespeichert und nach Jahr, Monat, Tag, Stunde und Minute in Unterordner archiviert\n• Transkripttext und Zusammenfassungen werden zusätzlich verschlüsselt in der lokalen Datenbank gespeichert\n• API-Keys werden sicher im macOS-Keychain / iOS-Keychain gespeichert\n• Beim Deinstallieren der App werden alle Daten gelöscht (außer Audiodateien im Dokumente-Verzeichnis, die manuell gelöscht werden müssen)",
        "• Los archivos de grabación, las transcripciones y los resúmenes se guardan juntos en la carpeta Memonta dentro de tu directorio Documentos (~/Documents/Memonta/), archivados en subcarpetas por año, mes, día, hora y minuto\n• El texto de transcripción y los resúmenes también se almacenan cifrados en la base de datos local\n• Las claves de API se almacenan de forma segura mediante el Llavero de macOS / iOS\n• Desinstalar la app borra todos los datos (excepto los archivos de audio del directorio Documentos, que deben eliminarse manualmente)",
        "• I file di registrazione, le trascrizioni e i riepiloghi sono archiviati insieme nella cartella Memonta della tua cartella Documenti (~/Documents/Memonta/), archiviati in sottocartelle per anno, mese, giorno, ora e minuto\n• Il testo della trascrizione e i riepiloghi sono inoltre memorizzati cifrati nel database locale\n• Le API Key sono archiviate in modo sicuro tramite il Portachiavi di macOS / iOS\n• Disinstallando l'app vengono cancellati tutti i dati (tranne i file audio nella cartella Documenti, da eliminare manualmente)",
        "• Os arquivos de gravação, as transcrições e os resumos são armazenados juntos na pasta Memonta dentro do seu diretório Documentos (~/Documents/Memonta/), arquivados em subpastas por ano, mês, dia, hora e minuto\n• O texto da transcrição e os resumos também são armazenados criptografados no banco de dados local\n• As chaves de API são armazenadas com segurança usando o Keychain do macOS / iOS\n• Desinstalar o app apaga todos os dados (exceto os arquivos de áudio no diretório Documentos, que devem ser excluídos manualmente)",
        "• Файлы записей, расшифровки и сводки хранятся вместе в папке Memonta в вашем каталоге «Документы» (~/Documents/Memonta/) и архивируются в подпапки по году, месяцу, дню, часу и минуте\n• Текст расшифровки и сводки также хранятся в зашифрованном виде в локальной базе данных\n• Ключи API надёжно хранятся в macOS Keychain / iOS Keychain\n• При удалении приложения все данные стираются (кроме аудиофайлов в каталоге «Документы», которые нужно удалить вручную)",
        "• تُخزَّن ملفات التسجيل والنصوص والملخصات معًا في مجلد Memonta داخل دليل المستندات لديك (~/Documents/Memonta/)، وتُؤرشف في مجلدات فرعية حسب السنة والشهر واليوم والساعة والدقيقة\n• يُخزَّن نص النسخ والملخصات أيضًا مشفَّرين في قاعدة البيانات المحلية\n• تُخزَّن مفاتيح API بأمان باستخدام سلسلة مفاتيح macOS / iOS\n• تؤدي إزالة تثبيت التطبيق إلى محو جميع البيانات (باستثناء الملفات الصوتية في دليل المستندات، التي يجب حذفها يدويًا)",
        "• रिकॉर्डिंग फ़ाइलें, ट्रांसक्रिप्ट रिकॉर्ड और सारांश आपके Documents निर्देशिका में Memonta फ़ोल्डर (~/Documents/Memonta/) में एक साथ संग्रहीत होते हैं, और वर्ष, माह, दिन, घंटे व मिनट के अनुसार उप-फ़ोल्डरों में संग्रहित किए जाते हैं\n• ट्रांसक्रिप्ट टेक्स्ट और सारांश स्थानीय डेटाबेस में एन्क्रिप्टेड भी संग्रहीत होते हैं\n• API Key को macOS Keychain / iOS Keychain का उपयोग करके सुरक्षित रूप से संग्रहीत किया जाता है\n• ऐप अनइंस्टॉल करने पर सारा डेटा मिट जाएगा (Documents निर्देशिका की ऑडियो फ़ाइलों को छोड़कर, जिन्हें मैन्युअल रूप से हटाना होगा)",
        "• ไฟล์บันทึกเสียง บันทึกการถอดเสียง และสรุปจะถูกจัดเก็บไว้ด้วยกันในโฟลเดอร์ Memonta ภายใต้ไดเรกทอรีเอกสารของคุณ (~/Documents/Memonta/) โดยจัดเก็บเป็นโฟลเดอร์ย่อยตามปี เดือน วัน ชั่วโมง และนาที\n• ข้อความถอดเสียงและสรุปจะถูกจัดเก็บแบบเข้ารหัสในฐานข้อมูลในเครื่องด้วย\n• API Key ถูกจัดเก็บอย่างปลอดภัยโดยใช้ macOS Keychain / iOS Keychain\n• การถอนการติดตั้งแอปจะลบข้อมูลทั้งหมด (ยกเว้นไฟล์เสียงในไดเรกทอรีเอกสาร ซึ่งต้องลบด้วยตนเอง)",
        "• Tệp ghi âm, bản gỡ băng và bản tóm tắt được lưu cùng nhau trong thư mục Memonta thuộc thư mục Documents của bạn (~/Documents/Memonta/), được lưu trữ vào các thư mục con theo năm, tháng, ngày, giờ và phút\n• Văn bản gỡ băng và bản tóm tắt cũng được lưu mã hóa trong cơ sở dữ liệu cục bộ\n• API Key được lưu trữ an toàn bằng macOS Keychain / iOS Keychain\n• Gỡ cài đặt ứng dụng sẽ xóa toàn bộ dữ liệu (trừ các tệp âm thanh trong thư mục Documents, phải xóa thủ công)",
        "• File rekaman, transkrip, dan ringkasan disimpan bersama di folder Memonta dalam direktori Documents Anda (~/Documents/Memonta/), diarsipkan ke subfolder berdasarkan tahun, bulan, hari, jam, dan menit\n• Teks transkrip dan ringkasan juga disimpan terenkripsi di basis data lokal\n• API Key disimpan dengan aman menggunakan macOS Keychain / iOS Keychain\n• Menghapus instalasi aplikasi akan menghapus semua data (kecuali file audio di direktori Documents, yang harus dihapus secara manual)",
        "• Kayıt dosyaları, dökümler ve özetler, Belgeler dizininizdeki Memonta klasöründe (~/Documents/Memonta/) birlikte saklanır ve yıl, ay, gün, saat ve dakikaya göre alt klasörlere arşivlenir\n• Döküm metni ve özetler ayrıca yerel veritabanında şifrelenmiş olarak saklanır\n• API Key'ler macOS Keychain / iOS Keychain kullanılarak güvenle saklanır\n• Uygulamayı kaldırmak tüm verileri siler (Belgeler dizinindeki ses dosyaları hariç; bunlar elle silinmelidir)",
        "• Opnamebestanden, transcripties en samenvattingen worden samen opgeslagen in de Memonta-map onder je Documenten-map (~/Documents/Memonta/), gearchiveerd in submappen op jaar, maand, dag, uur en minuut\n• Transcriptietekst en samenvattingen worden ook versleuteld opgeslagen in de lokale database\n• API Keys worden veilig opgeslagen met macOS Keychain / iOS Keychain\n• Bij het verwijderen van de app worden alle gegevens gewist (behalve audiobestanden in de Documenten-map, die handmatig moeten worden verwijderd)",
        "• Pliki nagrań, transkrypcje i podsumowania są przechowywane razem w folderze Memonta w katalogu Dokumenty (~/Documents/Memonta/) i archiwizowane w podfolderach według roku, miesiąca, dnia, godziny i minuty\n• Tekst transkrypcji i podsumowania są również przechowywane w zaszyfrowanej formie w lokalnej bazie danych\n• Klucze API są bezpiecznie przechowywane w macOS Keychain / iOS Keychain\n• Odinstalowanie aplikacji usuwa wszystkie dane (z wyjątkiem plików audio w katalogu Dokumenty, które trzeba usunąć ręcznie)",
        "• Файли записів, розшифровки та підсумки зберігаються разом у теці Memonta у вашій теці «Документи» (~/Documents/Memonta/) й архівуються в підтеки за роком, місяцем, днем, годиною та хвилиною\n• Текст розшифровки та підсумки також зберігаються зашифрованими в локальній базі даних\n• Ключі API надійно зберігаються за допомогою macOS Keychain / iOS Keychain\n• Видалення застосунку стирає всі дані (крім аудіофайлів у теці «Документи», які потрібно видалити вручну)",
        "• Inspelningsfiler, transkriptioner och sammanfattningar lagras tillsammans i Memonta-mappen under din Dokument-mapp (~/Documents/Memonta/) och arkiveras i undermappar efter år, månad, dag, timme och minut\n• Transkriptionstext och sammanfattningar lagras också krypterade i den lokala databasen\n• API-nycklar lagras säkert med macOS Keychain / iOS Keychain\n• Att avinstallera appen raderar alla data (utom ljudfiler i Dokument-mappen, som måste tas bort manuellt)",
    ],
)


def main():
    with open(CATALOG, encoding='utf-8') as f:
        catalog = json.load(f)
    existing = catalog['strings']
    filled = missing_key = 0
    for key, vals in T.items():
        entry = existing.get(key)
        if entry is None:
            print(f'⚠️ 目录中无此 key，跳过：{key[:30]}')
            missing_key += 1
            continue
        locs = entry.setdefault('localizations', {})
        if 'zh-Hans' not in locs:
            locs['zh-Hans'] = {'stringUnit': {'state': 'translated', 'value': key}}
        for lang, val in zip(LANGS, vals):
            if lang in locs:
                continue
            locs[lang] = {'stringUnit': {'state': 'translated', 'value': val}}
            filled += 1
    with open(CATALOG, 'w', encoding='utf-8') as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2, sort_keys=False)
        f.write('\n')
    print(f'完成：{len(T)} 条 key，新增 {filled} 条译文（缺失 key {missing_key} 条）')


if __name__ == '__main__':
    main()
