#!/usr/bin/env python3
# 为截图功能新增本地化键（20 种语言）写入 Localizable.xcstrings
import json

CATALOG = 'Memonta/Resources/Localizable.xcstrings'
LANGS = ['zh-Hant', 'en', 'ja', 'ko', 'fr', 'de', 'es', 'it', 'pt', 'ru',
         'ar', 'hi', 'th', 'vi', 'id', 'tr', 'nl', 'pl', 'uk', 'sv']

T = {}


def add(key, vals):
    assert len(vals) == 20, key
    T[key] = vals

# ---- batch 1: 基础术语 ----
add('截图', ['截圖', 'Screenshot', 'スクリーンショット', '스크린샷', 'Capture d’écran', 'Screenshot', 'Captura de pantalla', 'Screenshot', 'Captura de ecrã', 'Скриншот', 'لقطة الشاشة', 'स्क्रीनशॉट', 'ภาพหน้าจอ', 'Ảnh chụp màn hình', 'Tangkapan layar', 'Ekran görüntüsü', 'Schermafbeelding', 'Zrzut ekranu', 'Знімок екрана', 'Skärmdump'])
add('截图 %@', ['截圖 %@', 'Screenshot %@', 'スクリーンショット %@', '스크린샷 %@', 'Capture d’écran %@', 'Screenshot %@', 'Captura de pantalla %@', 'Screenshot %@', 'Captura de ecrã %@', 'Скриншот %@', 'لقطة الشاشة %@', 'स्क्रीनशॉट %@', 'ภาพหน้าจอ %@', 'Ảnh chụp màn hình %@', 'Tangkapan layar %@', 'Ekran görüntüsü %@', 'Schermafbeelding %@', 'Zrzut ekranu %@', 'Знімок екрана %@', 'Skärmdump %@'])
add('区域截图', ['區域截圖', 'Region Capture', '領域切り取り', '영역 캡처', 'Capture de zone', 'Bereichsaufnahme', 'Captura de zona', 'Cattura area', 'Captura de região', 'Захват области', 'التقاط المنطقة', 'क्षेत्र कैप्चर', 'จับภาพบริเวณ', 'Chụp vùng', 'Tangkapan area', 'Bölge Yakalama', 'Gebied vastleggen', 'Zrzut obszaru', 'Захоплення області', 'Områdesbild'])
add('截取窗口', ['截取視窗', 'Capture Window', 'ウィンドウをキャプチャ', '창 캡처', 'Capturer la fenêtre', 'Fenster aufnehmen', 'Capturar ventana', 'Cattura finestra', 'Capturar janela', 'Захват окна', 'التقاط النافذة', 'विंडो कैप्चर', 'จับภาพหน้าต่าง', 'Chụp cửa sổ', 'Tangkapan jendela', 'Pencere Yakala', 'Venster vastleggen', 'Zrzut okna', 'Захоплення вікна', 'Fönsterbild'])
add('截取全屏', ['截取全螢幕', 'Capture Full Screen', '全画面をキャプチャ', '전체 화면 캡처', 'Capturer tout l’écran', 'Vollbild aufnehmen', 'Capturar pantalla completa', 'Cattura schermo intero', 'Capturar ecrã inteiro', 'Захват всего экрана', 'التقاط الشاشة الكاملة', 'पूरी स्क्रीन कैप्चर', 'จับภาพทั้งหน้าจอ', 'Chụp toàn màn hình', 'Tangkapan layar penuh', 'Tüm Ekranı Yakala', 'Volledig scherm vastleggen', 'Zrzut całego ekranu', 'Захоплення всього екрана', 'Helskärmsbild'])
add('新建区域截图', ['新建區域截圖', 'New Region Screenshot', '新しい領域切り取り', '새 영역 스크린샷', 'Nouvelle capture de zone', 'Neuer Bereichs-Screenshot', 'Nueva captura de zona', 'Nuova cattura area', 'Nova captura de região', 'Новый скриншот области', 'لقطة منطقة جديدة', 'नया क्षेत्र स्क्रीनशॉट', 'ภาพหน้าจอบริเวณใหม่', 'Ảnh chụp vùng mới', 'Tangkapan area baru', 'Yeni Bölge Ekran Görüntüsü', 'Nieuwe gebiedsschermafbeelding', 'Nowy zrzut obszaru', 'Новий знімок області', 'Ny områdesbild'])
add('新建区域截图（全局热键 ⌥⌘S）', ['新建區域截圖（全域熱鍵 ⌥⌘S）', 'New region screenshot (global hotkey ⌥⌘S)', '新しい領域切り取り（グローバルホットキー ⌥⌘S）', '새 영역 스크린샷(전역 단축키 ⌥⌘S)', 'Nouvelle capture de zone (raccourci global ⌥⌘S)', 'Neuer Bereichs-Screenshot (globaler Hotkey ⌥⌘S)', 'Nueva captura de zona (atajo global ⌥⌘S)', 'Nuova cattura area (scorciatoia globale ⌥⌘S)', 'Nova captura de região (atalho global ⌥⌘S)', 'Новый скриншот области (глобальная горячая клавиша ⌥⌘S)', 'لقطة منطقة جديدة (مفتاح اختصار عام ⌥⌘S)', 'नया क्षेत्र स्क्रीनशॉट (ग्लोबल हॉटकी ⌥⌘S)', 'ภาพหน้าจอบริเวณใหม่ (ปุ่มลัดสากล ⌥⌘S)', 'Ảnh chụp vùng mới (phím tắt toàn cục ⌥⌘S)', 'Tangkapan area baru (hotkey global ⌥⌘S)', 'Yeni bölge ekran görüntüsü (genel kısayol ⌥⌘S)', 'Nieuwe gebiedsschermafbeelding (algemene sneltoets ⌥⌘S)', 'Nowy zrzut obszaru (globalny skrót ⌥⌘S)', 'Новий знімок області (глобальна гаряча клавіша ⌥⌘S)', 'Ny områdesbild (global kortkommando ⌥⌘S)'])

# ---- batch 2: OCR/总结/状态 ----
add('识别文字', ['識別文字', 'Recognize Text', 'テキストを認識', '텍스트 인식', 'Reconnaître le texte', 'Text erkennen', 'Reconocer texto', 'Riconosci testo', 'Reconhecer texto', 'Распознать текст', 'التعرف على النص', 'टेक्स्ट पहचानें', 'รู้จำข้อความ', 'Nhận dạng văn bản', 'Kenali teks', 'Metni Tanı', 'Tekst herkennen', 'Rozpoznaj tekst', 'Розпізнати текст', 'Känn igen text'])
add('正在识别文字...', ['正在識別文字...', 'Recognizing text...', 'テキストを認識中...', '텍스트 인식 중...', 'Reconnaissance du texte...', 'Text wird erkannt...', 'Reconociendo texto...', 'Riconoscimento del testo...', 'A reconhecer texto...', 'Распознавание текста...', 'جارٍ التعرف على النص...', 'टेक्स्ट पहचाना जा रहा है...', 'กำลังรู้จำข้อความ...', 'Đang nhận dạng văn bản...', 'Mengenali teks...', 'Metin tanınıyor...', 'Tekst wordt herkend...', 'Rozpoznawanie tekstu...', 'Розпізнавання тексту...', 'Känner igen text...'])
add('识别中...', ['識別中...', 'Recognizing...', '認識中...', '인식 중...', 'Reconnaissance...', 'Erkennung...', 'Reconociendo...', 'Riconoscimento...', 'A reconhecer...', 'Распознавание...', 'جارٍ التعرف...', 'पहचाना जा रहा है...', 'กำลังรู้จำ...', 'Đang nhận dạng...', 'Mengenali...', 'Tanınıyor...', 'Herkennen...', 'Rozpoznawanie...', 'Розпізнавання...', 'Känner igen...'])
add('截图总结', ['截圖總結', 'Screenshot Summary', 'スクリーンショット要約', '스크린샷 요약', 'Résumé de la capture', 'Screenshot-Zusammenfassung', 'Resumen de captura', 'Riepilogo screenshot', 'Resumo da captura', 'Сводка скриншота', 'ملخص لقطة الشاشة', 'स्क्रीनशॉट सारांश', 'สรุปภาพหน้าจอ', 'Tóm tắt ảnh chụp màn hình', 'Ringkasan tangkapan layar', 'Ekran Görüntüsü Özeti', 'Samenvatting schermafbeelding', 'Podsumowanie zrzutu ekranu', 'Зведення знімка екрана', 'Sammanfattning av skärmdump'])
add('生成中...', ['生成中...', 'Generating...', '生成中...', '생성 중...', 'Génération...', 'Wird generiert...', 'Generando...', 'Generazione...', 'A gerar...', 'Генерация...', 'جارٍ الإنشاء...', 'जेनरेट हो रहा है...', 'กำลังสร้าง...', 'Đang tạo...', 'Menghasilkan...', 'Oluşturuluyor...', 'Genereren...', 'Generowanie...', 'Генерування...', 'Genererar...'])
add('含标注', ['含標註', 'Annotated', '注釈あり', '주석 포함', 'Annoté', 'Annotiert', 'Anotado', 'Annotato', 'Anotado', 'С аннотацией', 'مُعلَّق', 'एनोटेटेड', 'มีคำอธิบาย', 'Có chú thích', 'Beranotasi', 'Açıklamalı', 'Geannoteerd', 'Z adnotacją', 'З анотацією', 'Med anteckning'])

# ---- batch 3: 标注工具 ----
add('复制到剪贴板', ['複製到剪貼簿', 'Copy to Clipboard', 'クリップボードにコピー', '클립보드로 복사', 'Copier dans le presse-papiers', 'In die Zwischenablage kopieren', 'Copiar al portapapeles', 'Copia negli appunti', 'Copiar para a área de transferência', 'Скопировать в буфер обмена', 'نسخ إلى الحافظة', 'क्लिपबोर्ड पर कॉपी करें', 'คัดลอกไปยังคลิปบอร์ด', 'Sao chép vào bảng tạm', 'Salin ke papan klip', 'Panoya Kopyala', 'Kopieer naar klembord', 'Skopiuj do schowka', 'Копіювати в буфер обміну', 'Kopiera till urklipp'])
add('撤销', ['撤銷', 'Undo', '取り消す', '실행 취소', 'Annuler', 'Widerrufen', 'Deshacer', 'Annulla', 'Desfazer', 'Отменить', 'تراجع', 'पूर्ववत करें', 'เลิกทำ', 'Hoàn tác', 'Urungkan', 'Geri Al', 'Ongedaan maken', 'Cofnij', 'Скасувати', 'Ångra'])
add('重做', ['重做', 'Redo', 'やり直す', '다시 실행', 'Rétablir', 'Wiederholen', 'Rehacer', 'Ripeti', 'Refazer', 'Повторить', 'إعادة', 'फिर करें', 'ทำซ้ำ', 'Làm lại', 'Ulangi', 'Yinele', 'Opnieuw', 'Ponów', 'Повернути', 'Gör om'])
add('文字', ['文字', 'Text', 'テキスト', '텍스트', 'Texte', 'Text', 'Texto', 'Testo', 'Texto', 'Текст', 'نص', 'टेक्स्ट', 'ข้อความ', 'Văn bản', 'Teks', 'Metin', 'Tekst', 'Tekst', 'Текст', 'Text'])
add('椭圆', ['橢圓', 'Ellipse', '楕円', '타원', 'Ellipse', 'Ellipse', 'Elipse', 'Ellisse', 'Elipse', 'Овал', 'قطع ناقص', 'अंडाकार', 'วงรี', 'Hình elip', 'Elips', 'Elips', 'Ellips', 'Elipsa', 'Еліпс', 'Ellips'])
add('画笔', ['畫筆', 'Pen', 'ペン', '펜', 'Stylet', 'Stift', 'Lápiz', 'Penna', 'Caneta', 'Перо', 'قلم', 'पेन', 'ปากกา', 'Bút vẽ', 'Pena', 'Kalem', 'Pen', 'Pióro', 'Перо', 'Penna'])
add('矩形', ['矩形', 'Rectangle', '四角形', '사각형', 'Rectangle', 'Rechteck', 'Rectángulo', 'Rettangolo', 'Retângulo', 'Прямоугольник', 'مستطيل', 'आयत', 'สี่เหลี่ยมผืนผ้า', 'Hình chữ nhật', 'Persegi panjang', 'Dikdörtgen', 'Rechthoek', 'Prostokąt', 'Прямокутник', 'Rektangel'])
add('箭头', ['箭頭', 'Arrow', '矢印', '화살표', 'Flèche', 'Pfeil', 'Flecha', 'Freccia', 'Seta', 'Стрелка', 'سهم', 'तीर', 'ลูกศร', 'Mũi tên', 'Panah', 'Ok', 'Pijl', 'Strzałka', 'Стрілка', 'Pil'])
add('马赛克', ['馬賽克', 'Mosaic', 'モザイク', '모자이크', 'Mosaïque', 'Mosaik', 'Mosaico', 'Mosaico', 'Mosaico', 'Мозаика', 'فسيفساء', 'मोज़ेक', 'โมเสก', 'Khảm', 'Mosaik', 'Mozaik', 'Mozaïek', 'Mozaika', 'Мозаїка', 'Mosaik'])
add('输入文字', ['輸入文字', 'Enter Text', 'テキストを入力', '텍스트 입력', 'Saisir le texte', 'Text eingeben', 'Introducir texto', 'Inserisci testo', 'Inserir texto', 'Введите текст', 'أدخل النص', 'टेक्स्ट दर्ज करें', 'ป้อนข้อความ', 'Nhập văn bản', 'Masukkan teks', 'Metin Gir', 'Tekst invoeren', 'Wprowadź tekst', 'Введіть текст', 'Ange text'])
add('标注颜色', ['標註顏色', 'Annotation Color', '注釈の色', '주석 색상', 'Couleur d’annotation', 'Anmerkungsfarbe', 'Color de anotación', 'Colore annotazione', 'Cor da anotação', 'Цвет аннотации', 'لون التعليق التوضيحي', 'एनोटेशन रंग', 'สีคำอธิบาย', 'Màu chú thích', 'Warna anotasi', 'Açıklama Rengi', 'Annotatiekleur', 'Kolor adnotacji', 'Колір анотації', 'Anteckningsfärg'])
add('确认保存', ['確認儲存', 'Confirm Save', '保存を確認', '저장 확인', 'Confirmer l’enregistrement', 'Sichern bestätigen', 'Confirmar guardado', 'Conferma salvataggio', 'Confirmar guardar', 'Подтвердить сохранение', 'تأكيد الحفظ', 'सहेजने की पुष्टि करें', 'ยืนยันบันทึก', 'Xác nhận lưu', 'Konfirmasi simpan', 'Kaydetmeyi Onayla', 'Opslaan bevestigen', 'Potwierdź zapis', 'Підтвердити збереження', 'Bekräfta spara'])

# ---- batch 4: 权限与失败提示 ----
add('生成截图失败，请重试', ['生成截圖失敗，請重試', 'Failed to generate screenshot, please retry', 'スクリーンショットの生成に失敗しました。再試行してください', '스크린샷 생성에 실패했습니다. 다시 시도하세요', 'Échec de la génération de la capture, réessayez', 'Screenshot konnte nicht erstellt werden, bitte erneut versuchen', 'No se pudo generar la captura, reintente', 'Generazione dello screenshot non riuscita, riprova', 'Falha ao gerar a captura, tente novamente', 'Не удалось создать скриншот, повторите попытку', 'فشل إنشاء لقطة الشاشة، أعد المحاولة', 'स्क्रीनशॉट बनाने में विफल, कृपया पुनः प्रयास करें', 'สร้างภาพหน้าจอไม่สำเร็จ โปรดลองอีกครั้ง', 'Tạo ảnh chụp màn hình thất bại, hãy thử lại', 'Gagal membuat tangkapan layar, coba lagi', 'Ekran görüntüsü oluşturulamadı, lütfen tekrar deneyin', 'Schermafbeelding kon niet worden gemaakt, probeer opnieuw', 'Nie udało się utworzyć zrzutu ekranu, spróbuj ponownie', 'Не вдалося створити знімок екрана, спробуйте ще раз', 'Kunde inte skapa skärmdump, försök igen'])
add('无法捕获屏幕内容，请检查屏幕录制权限', ['無法擷取螢幕內容，請檢查螢幕錄製權限', 'Unable to capture screen content, please check screen recording permission', '画面の内容をキャプチャできません。画面収録権限を確認してください', '화면 내용을 캡처할 수 없습니다. 화면 녹화 권한을 확인하세요', 'Impossible de capturer l’écran, vérifiez l’autorisation d’enregistrement d’écran', 'Bildschirminhalt konnte nicht aufgenommen werden, bitte Berechtigung prüfen', 'No se puede capturar la pantalla, compruebe el permiso de grabación', 'Impossibile acquisire lo schermo, verificare l’autorizzazione', 'Não é possível capturar o ecrã, verifique a permissão de gravação', 'Не удалось захватить содержимое экрана, проверьте разрешение на запись экрана', 'لا يمكن التقاط محتوى الشاشة، تحقق من إذن تسجيل الشاشة', 'स्क्रीन सामग्री कैप्चर नहीं हो सकी, स्क्रीन रिकॉर्डिंग अनुमति जांचें', 'ไม่สามารถจับภาพเนื้อหาหน้าจอได้ โปรดตรวจสอบสิทธิ์การบันทึกหน้าจอ', 'Không thể chụp nội dung màn hình, hãy kiểm tra quyền ghi màn hình', 'Tidak dapat menangkap konten layar, periksa izin perekaman layar', 'Ekran içeriği yakalanamadı, ekran kaydı iznini kontrol edin', 'Schermcontent kon niet worden vastgelegd, controleer de opnamemachtiging', 'Nie można przechwycić zawartości ekranu, sprawdź uprawnienia nagrywania', 'Не вдалося захопити вміст екрана, перевірте дозвіл на запис екрана', 'Kunde inte fånga skärminnehåll, kontrollera inspelningsbehörigheten'])
add('需要屏幕录制权限', ['需要螢幕錄製權限', 'Screen Recording Permission Required', '画面収録権限が必要です', '화면 녹화 권한이 필요합니다', 'Autorisation d’enregistrement d’écran requise', 'Bildschirmaufnahme-Berechtigung erforderlich', 'Se requiere permiso de grabación de pantalla', 'Autorizzazione registrazione schermo richiesta', 'Permissão de gravação de ecrã necessária', 'Требуется разрешение на запись экрана', 'إذن تسجيل الشاشة مطلوب', 'स्क्रीन रिकॉर्डिंग अनुमति आवश्यक', 'จำเป็นต้องมีสิทธิ์การบันทึกหน้าจอ', 'Cần có quyền ghi màn hình', 'Izin perekaman layar diperlukan', 'Ekran Kaydı İzni Gerekli', 'Toestemming voor schermopname vereist', 'Wymagane uprawnienie do nagrywania ekranu', 'Потрібен дозвіл на запис екрана', 'Behörighet för skärminspelning krävs'])
add('请在「系统设置 → 隐私与安全性 → 屏幕录制」中允许 Memonta，然后重新触发截图。', ['請在「系統設定 → 隱私權與安全性 → 螢幕錄製」中允許 Memonta，然後重新觸發截圖。', 'Please allow Memonta in “System Settings → Privacy & Security → Screen Recording”, then trigger the screenshot again.', '「システム設定 → プライバシーとセキュリティ → 画面収録」で Memonta を許可してから、再度スクリーンショットを実行してください。', '「시스템 설정 → 개인정보 보호 및 보안 → 화면 녹화」에서 Memonta를 허용한 후 다시 스크린샷을 실행하세요.', 'Veuillez autoriser Memonta dans « Réglages Système → Confidentialité et sécurité → Enregistrement de l’écran », puis relancez la capture.', 'Bitte erlauben Sie Memonta unter „Systemeinstellungen → Datenschutz & Sicherheit → Bildschirmaufnahme“ und lösen Sie dann den Screenshot erneut aus.', 'Permita Memonta en «Ajustes del Sistema → Privacidad y seguridad → Grabación de pantalla» y vuelva a capturar.', 'Consenti Memonta in “Impostazioni di Sistema → Privacy e sicurezza → Registrazione schermo”, quindi riavvia lo screenshot.', 'Permita o Memonta em “Ajustes do Sistema → Privacidade e Segurança → Gravação de Ecrã” e repita a captura.', 'Разрешите Memonta в «Системные настройки → Конфиденциальность и безопасность → Запись экрана», затем повторите скриншот.', 'يرجى السماح لـ Memonta في «إعدادات النظام → الخصوصية والأمان → تسجيل الشاشة» ثم إعادة التقاط لقطة الشاشة.', 'कृपया “सिस्टम सेटिंग्स → प्राइवेसी और सिक्योरिटी → स्क्रीन रिकॉर्डिंग” में Memonta की अनुमति दें, फिर स्क्रीनशॉट दोबारा लें।', 'โปรดอนุญาต Memonta ใน "การตั้งค่าระบบ → ความเป็นส่วนตัวและความปลอดภัย → การบันทึกหน้าจอ" แล้วถ่ายภาพหน้าจออีกครั้ง', 'Hãy cho phép Memonta trong “Cài đặt hệ thống → Quyền riêng tư và bảo mật → Ghi màn hình”, rồi chụp lại.', 'Izinkan Memonta di “Pengaturan Sistem → Privasi & Keamanan → Perekaman Layar”, lalu ambil tangkapan layar lagi.', 'Memonta’ya “Sistem Ayarları → Gizlilik ve Güvenlik → Ekran Kaydı” bölümünde izin verin, ardından ekran görüntüsünü tekrar alın.', 'Sta Memonta toe in “Systeeminstellingen → Privacy en beveiliging → Schermopname” en leg de schermafbeelding opnieuw vast.', 'Zezwól na Memonta w „Ustawienia systemowe → Prywatność i bezpieczeństwo → Nagrywanie ekranu”, a następnie ponów zrzut ekranu.', 'Дозвольте Memonta у «Системні налаштування → Конфіденційність і безпека → Запис екрана», потім повторіть знімок.', 'Tillåt Memonta i ”Systeminställningar → Integritet och säkerhet → Skärminspelning” och ta sedan skärmdumpen igen.'])
add('打开系统设置', ['打開系統設定', 'Open System Settings', 'システム設定を開く', '시스템 설정 열기', 'Ouvrir les Réglages Système', 'Systemeinstellungen öffnen', 'Abrir Ajustes del Sistema', 'Apri Impostazioni di Sistema', 'Abrir Ajustes do Sistema', 'Открыть системные настройки', 'افتح إعدادات النظام', 'सिस्टम सेटिंग्स खोलें', 'เปิดการตั้งค่าระบบ', 'Mở Cài đặt hệ thống', 'Buka Pengaturan Sistem', 'Sistem Ayarlarını Aç', 'Systeeminstellingen openen', 'Otwórz ustawienia systemowe', 'Відкрити системні налаштування', 'Öppna systeminställningar'])
add('截图失败', ['截圖失敗', 'Screenshot Failed', 'スクリーンショットに失敗', '스크린샷 실패', 'Échec de la capture', 'Screenshot fehlgeschlagen', 'Error de captura', 'Screenshot non riuscito', 'Falha na captura', 'Не удалось сделать скриншот', 'فشل التقاط الشاشة', 'स्क्रीनशॉट विफल', 'ภาพหน้าจอล้มเหลว', 'Chụp ảnh màn hình thất bại', 'Tangkapan layar gagal', 'Ekran görüntüsü alınamadı', 'Schermafbeelding mislukt', 'Nie udało się zrobić zrzutu', 'Не вдалося зробити знімок', 'Skärmdump misslyckades'])
add('无法解析图片数据', ['無法解析圖片資料', 'Unable to parse image data', '画像データを解析できません', '이미지 데이터를 분석할 수 없습니다', 'Impossible d’analyser les données d’image', 'Bilddaten konnten nicht analysiert werden', 'No se pueden analizar los datos de la imagen', 'Impossibile analizzare i dati dell’immagine', 'Não é possível analisar os dados da imagem', 'Не удалось разобрать данные изображения', 'لا يمكن تحليل بيانات الصورة', 'इमेज डेटा पार्स नहीं हो सका', 'ไม่สามารถแยกวิเคราะห์ข้อมูลภาพได้', 'Không thể phân tích dữ liệu ảnh', 'Tidak dapat mengurai data gambar', 'Görsel verileri ayrıştırılamadı', 'Afbeeldingsdata kon niet worden geparseerd', 'Nie można przeanalizować danych obrazu', 'Не вдалося розібрати дані зображення', 'Kunde inte tolka bilddata'])
add('在 Finder 中显示', ['在 Finder 中顯示', 'Show in Finder', 'Finder で表示', 'Finder에서 보기', 'Afficher dans le Finder', 'Im Finder anzeigen', 'Mostrar en el Finder', 'Mostra nel Finder', 'Mostrar no Finder', 'Показать в Finder', 'إظهار في Finder', 'Finder में दिखाएँ', 'แสดงใน Finder', 'Hiển thị trong Finder', 'Tampilkan di Finder', 'Finder’da Göster', 'Toon in Finder', 'Pokaż w Finderze', 'Показати у Finder', 'Visa i Finder'])
add('复制识别文字', ['複製識別文字', 'Copy Recognized Text', '認識したテキストをコピー', '인식된 텍스트 복사', 'Copier le texte reconnu', 'Erkannten Text kopieren', 'Copiar texto reconocido', 'Copia testo riconosciuto', 'Copiar texto reconhecido', 'Скопировать распознанный текст', 'نسخ النص المُتَعَرَّف عليه', 'पहचाना गया टेक्स्ट कॉपी करें', 'คัดลอกข้อความที่รู้จำ', 'Sao chép văn bản đã nhận dạng', 'Salin teks yang dikenali', 'Tanınan Metni Kopyala', 'Herkende tekst kopiëren', 'Skopiuj rozpoznany tekst', 'Копіювати розпізнаний текст', 'Kopiera igenkänd text'])

# ---- batch 5: OCR/保存错误 ----
add('OCR 识别失败：%@', ['OCR 識別失敗：%@', 'OCR failed: %@', 'OCR 認識に失敗：%@', 'OCR 인식 실패: %@', 'Échec OCR : %@', 'OCR fehlgeschlagen: %@', 'Fallo de OCR: %@', 'OCR non riuscito: %@', 'Falha de OCR: %@', 'Ошибка OCR: %@', 'فشل OCR: %@', 'OCR विफल: %@', 'OCR ล้มเหลว: %@', 'OCR thất bại: %@', 'OCR gagal: %@', 'OCR başarısız: %@', 'OCR mislukt: %@', 'Błąd OCR: %@', 'Помилка OCR: %@', 'OCR misslyckades: %@'])
add('OCR 结果保存失败，请重试。', ['OCR 結果儲存失敗，請重試。', 'Failed to save OCR result, please retry.', 'OCR 結果の保存に失敗しました。再試行してください。', 'OCR 결과 저장에 실패했습니다. 다시 시도하세요.', 'Échec de l’enregistrement du résultat OCR, réessayez.', 'OCR-Ergebnis konnte nicht gespeichert werden, bitte erneut versuchen.', 'No se pudo guardar el resultado de OCR, reintente.', 'Salvataggio del risultato OCR non riuscito, riprova.', 'Falha ao guardar o resultado de OCR, tente novamente.', 'Не удалось сохранить результат OCR, повторите попытку.', 'فشل حفظ نتيجة OCR، أعد المحاولة.', 'OCR परिणाम सहेजने में विफल, कृपया पुनः प्रयास करें।', 'บันทึกผล OCR ไม่สำเร็จ โปรดลองอีกครั้ง', 'Lưu kết quả OCR thất bại, hãy thử lại.', 'Gagal menyimpan hasil OCR, coba lagi.', 'OCR sonucu kaydedilemedi, lütfen tekrar deneyin.', 'OCR-resultaat kon niet worden opgeslagen, probeer opnieuw.', 'Nie udało się zapisać wyniku OCR, spróbuj ponownie.', 'Не вдалося зберегти результат OCR, спробуйте ще раз.', 'Kunde inte spara OCR-resultatet, försök igen.'])
add('保存截图文件失败：%@', ['儲存截圖檔案失敗：%@', 'Failed to save screenshot file: %@', 'スクリーンショットの保存に失敗：%@', '스크린샷 파일 저장 실패: %@', 'Échec de l’enregistrement de la capture : %@', 'Screenshot-Datei konnte nicht gespeichert werden: %@', 'No se pudo guardar el archivo de captura: %@', 'Salvataggio del file screenshot non riuscito: %@', 'Falha ao guardar o ficheiro da captura: %@', 'Не удалось сохранить файл скриншота: %@', 'فشل حفظ ملف لقطة الشاشة: %@', 'स्क्रीनशॉट फ़ाइल सहेजने में विफल: %@', 'บันทึกไฟล์ภาพหน้าจอไม่สำเร็จ: %@', 'Lưu tệp ảnh chụp màn hình thất bại: %@', 'Gagal menyimpan file tangkapan layar: %@', 'Ekran görüntüsü dosyası kaydedilemedi: %@', 'Schermafbeeldingsbestand kon niet worden opgeslagen: %@', 'Nie udało się zapisać pliku zrzutu ekranu: %@', 'Не вдалося зберегти файл знімка екрана: %@', 'Kunde inte spara skärmdumpsfilen: %@'])
add('保存标题失败：%@', ['儲存標題失敗：%@', 'Failed to save title: %@', 'タイトルの保存に失敗：%@', '제목 저장 실패: %@', 'Échec de l’enregistrement du titre : %@', 'Titel konnte nicht gespeichert werden: %@', 'No se pudo guardar el título: %@', 'Salvataggio del titolo non riuscito: %@', 'Falha ao guardar o título: %@', 'Не удалось сохранить заголовок: %@', 'فشل حفظ العنوان: %@', 'शीर्षक सहेजने में विफल: %@', 'บันทึกชื่อเรื่องไม่สำเร็จ: %@', 'Lưu tiêu đề thất bại: %@', 'Gagal menyimpan judul: %@', 'Başlık kaydedilemedi: %@', 'Titel kon niet worden opgeslagen: %@', 'Nie udało się zapisać tytułu: %@', 'Не вдалося зберегти заголовок: %@', 'Kunde inte spara titeln: %@'])
add('截图入库失败：%@', ['截圖入庫失敗：%@', 'Failed to archive screenshot: %@', 'スクリーンショットの保存に失敗：%@', '스크린샷 등록 실패: %@', 'Échec de l’archivage de la capture : %@', 'Screenshot konnte nicht archiviert werden: %@', 'No se pudo archivar la captura: %@', 'Archiviazione dello screenshot non riuscita: %@', 'Falha ao arquivar a captura: %@', 'Не удалось занести скриншот в базу: %@', 'فشل أرشفة لقطة الشاشة: %@', 'स्क्रीनशॉट संग्रहित करने में विफल: %@', 'จัดเก็บภาพหน้าจอไม่สำเร็จ: %@', 'Lưu ảnh chụp màn hình vào cơ sở dữ liệu thất bại: %@', 'Gagal mengarsipkan tangkapan layar: %@', 'Ekran görüntüsü arşivlenemedi: %@', 'Schermafbeelding kon niet worden gearchiveerd: %@', 'Nie udało się zarchiwizować zrzutu ekranu: %@', 'Не вдалося додати знімок до бази: %@', 'Kunde inte arkivera skärmdumpen: %@'])

# ---- batch 6: 总结/文件错误 ----
add('截图总结失败：%@', ['截圖總結失敗：%@', 'Screenshot summary failed: %@', 'スクリーンショット要約に失敗：%@', '스크린샷 요약 실패: %@', 'Échec du résumé de la capture : %@', 'Screenshot-Zusammenfassung fehlgeschlagen: %@', 'Fallo en el resumen de la captura: %@', 'Riepilogo dello screenshot non riuscito: %@', 'Falha no resumo da captura: %@', 'Ошибка сводки скриншота: %@', 'فشل ملخص لقطة الشاشة: %@', 'स्क्रीनशॉट सारांश विफल: %@', 'สรุปภาพหน้าจอล้มเหลว: %@', 'Tóm tắt ảnh chụp màn hình thất bại: %@', 'Ringkasan tangkapan layar gagal: %@', 'Ekran görüntüsü özeti başarısız: %@', 'Samenvatting van schermafbeelding mislukt: %@', 'Nie udało się podsumować zrzutu ekranu: %@', 'Помилка зведення знімка екрана: %@', 'Sammanfattning av skärmdump misslyckades: %@'])
add('截图文件不存在或无法读取，无法拆解待办。', ['截圖檔案不存在或無法讀取，無法拆解待辦。', 'Screenshot file missing or unreadable, unable to extract todos.', 'スクリーンショットファイルが存在しないか読み取れないため、待ち事項を抽出できません。', '스크린샷 파일이 없거나 읽을 수 없어 할 일을 추출할 수 없습니다.', 'Fichier de capture introuvable ou illisible, impossible d’extraire les tâches.', 'Screenshot-Datei fehlt oder ist unlesbar, Aufgaben können nicht extrahiert werden.', 'Falta el archivo de captura o no se puede leer, no se pueden extraer tareas.', 'File screenshot mancante o illeggibile, impossibile estrarre le attività.', 'Ficheiro da captura em falta ou ilegível, não é possível extrair tarefas.', 'Файл скриншота отсутствует или не читается, невозможно извлечь задачи.', 'ملف لقطة الشاشة غير موجود أو غير قابل للقراءة، لا يمكن استخراج المهام.', 'स्क्रीनशॉट फ़ाइल अनुपस्थित या अपठनीय है, कार्य निकाले नहीं जा सकते।', 'ไฟล์ภาพหน้าจอไม่มีหรืออ่านไม่ได้ จึงแยกสิ่งที่ต้องทำไม่ได้', 'Tệp ảnh chụp màn hình không tồn tại hoặc không đọc được, không thể trích xuất việc cần làm.', 'File tangkapan layar tidak ada atau tidak terbaca, tidak dapat mengekstrak tugas.', 'Ekran görüntüsü dosyası yok veya okunamıyor, görevler çıkarılamıyor.', 'Schermafbeeldingsbestand ontbreekt of is onleesbaar, taken kunnen niet worden geëxtraheerd.', 'Brak pliku zrzutu ekranu lub jest nieczytelny, nie można wyodrębnić zadań.', 'Файл знімка екрана відсутній або нечитабельний, неможливо витягти завдання.', 'Skärmdumpsfilen saknas eller kan inte läsas, uppgifter kan inte extraheras.'])
add('截图文件不存在或无法读取，无法生成总结。', ['截圖檔案不存在或無法讀取，無法生成總結。', 'Screenshot file missing or unreadable, unable to generate summary.', 'スクリーンショットファイルが存在しないか読み取れないため、要約を生成できません。', '스크린샷 파일이 없거나 읽을 수 없어 요약을 생성할 수 없습니다.', 'Fichier de capture introuvable ou illisible, impossible de générer le résumé.', 'Screenshot-Datei fehlt oder ist unlesbar, Zusammenfassung kann nicht erstellt werden.', 'Falta el archivo de captura o no se puede leer, no se puede generar el resumen.', 'File screenshot mancante o illeggibile, impossibile generare il riepilogo.', 'Ficheiro da captura em falta ou ilegível, não é possível gerar o resumo.', 'Файл скриншота отсутствует или не читается, невозможно создать сводку.', 'ملف لقطة الشاشة غير موجود أو غير قابل للقراءة، لا يمكن إنشاء الملخص.', 'स्क्रीनशॉट फ़ाइल अनुपस्थित या अपठनीय है, सारांश नहीं बनाया जा सकता।', 'ไฟล์ภาพหน้าจอไม่มีหรืออ่านไม่ได้ จึงสร้างสรุปไม่ได้', 'Tệp ảnh chụp màn hình không tồn tại hoặc không đọc được, không thể tạo tóm tắt.', 'File tangkapan layar tidak ada atau tidak terbaca, tidak dapat menghasilkan ringkasan.', 'Ekran görüntüsü dosyası yok veya okunamıyor, özet oluşturulamıyor.', 'Schermafbeeldingsbestand ontbreekt of is onleesbaar, samenvatting kan niet worden gegenereerd.', 'Brak pliku zrzutu ekranu lub jest nieczytelny, nie można wygenerować podsumowania.', 'Файл знімка екрана відсутній або нечитабельний, неможливо створити зведення.', 'Skärmdumpsfilen saknas eller kan inte läsas, sammanfattning kan inte skapas.'])
add('截图尚无 OCR、总结或待办内容，请先生成后再润色标题。', ['截圖尚無 OCR、總結或待辦內容，請先生成後再潤色標題。', 'The screenshot has no OCR, summary, or todo content yet. Generate content before polishing the title.', 'スクリーンショットにはOCR・要約・タスクがまだありません。先に生成してからタイトルを整形してください。', '스크린샷에 OCR, 요약 또는 할 일 내용이 아직 없습니다. 먼저 생성한 후 제목을 다듬으세요.', 'La capture n’a pas encore de contenu OCR, résumé ou tâches. Générez le contenu avant de peaufiner le titre.', 'Der Screenshot hat noch keinen OCR-, Zusammenfassungs- oder Aufgabeninhalt. Erstellen Sie zuerst Inhalte, bevor Sie den Titel verfeinern.', 'La captura aún no tiene contenido de OCR, resumen o tareas. Genere contenido antes de pulir el título.', 'Lo screenshot non ha ancora contenuti OCR, riepilogo o attività. Genera i contenuti prima di rifinire il titolo.', 'A captura ainda não tem conteúdo de OCR, resumo ou tarefas. Gere o conteúdo antes de refinar o título.', 'У скриншота пока нет содержимого OCR, сводки или задач. Сначала создайте содержимое, затем улучшайте заголовок.', 'لا تحتوي لقطة الشاشة بعد على محتوى OCR أو ملخص أو مهام. أنشئ المحتوى قبل تحسين العنوان.', 'स्क्रीनशॉट में अभी OCR, सारांश या कार्य सामग्री नहीं है। शीर्षक को बेहतर बनाने से पहले सामग्री बनाएं।', 'ภาพหน้าจอยังไม่มีเนื้อหา OCR สรุป หรือสิ่งที่ต้องทำ โปรดสร้างเนื้อหาก่อนปรับชื่อเรื่อง', 'Ảnh chụp màn hình chưa có nội dung OCR, tóm tắt hoặc việc cần làm. Hãy tạo nội dung trước khi trau chuốt tiêu đề.', 'Tangkapan layar belum memiliki konten OCR, ringkasan, atau tugas. Buat konten terlebih dahulu sebelum memperbaiki judul.', 'Ekran görüntüsünde henüz OCR, özet veya yapılacak içerik yok. Başlığı düzeltmeden önce içerik oluşturun.', 'De schermafbeelding heeft nog geen OCR-, samenvattings- of takeninhoud. Genereer eerst inhoud voordat u de titel verfijnt.', 'Zrzut ekranu nie ma jeszcze treści OCR, podsumowania ani zadań. Wygeneruj treść przed dopracowaniem tytułu.', 'Знімок екрана ще не має вмісту OCR, зведення чи завдань. Спочатку створіть вміст, а потім вдосконалюйте заголовок.', 'Skärmdumpen har ännu ingen OCR-, sammanfattnings- eller uppgiftsinnehåll. Skapa innehåll innan du förfinar titeln.'])
add('截图文件夹删除失败：%@。数据库记录已保留以防止数据复活，请手动删除文件夹后重试。', ['截圖資料夾刪除失敗：%@。資料庫記錄已保留以防止資料復活，請手動刪除資料夾後重試。', 'Failed to delete screenshot folder: %@. The database record was kept to prevent data resurrection. Delete the folder manually and retry.', 'スクリーンショットフォルダの削除に失敗：%@。データの復活を防ぐためデータベース記録は保持されます。手動でフォルダを削除して再試行してください。', '스크린샷 폴더 삭제 실패: %@. 데이터 부활을 방지하기 위해 데이터베이스 기록이 유지됩니다. 폴더를 수동으로 삭제한 후 다시 시도하세요.', 'Échec de la suppression du dossier de capture : %@. L’entrée de base de données a été conservée pour éviter la résurrection des données. Supprimez le dossier manuellement et réessayez.', 'Löschen des Screenshot-Ordners fehlgeschlagen: %@. Der Datenbankeintrag wurde zur Vermeidung von Datenwiederherstellung beibehalten. Löschen Sie den Ordner manuell und versuchen Sie es erneut.', 'Error al eliminar la carpeta de captura: %@. Se mantuvo el registro de la base de datos para evitar la resurrección de datos. Elimine la carpeta manualmente y reintente.', 'Eliminazione della cartella screenshot non riuscita: %@. Il record del database è stato mantenuto per evitare la resurrezione dei dati. Elimina manualmente la cartella e riprova.', 'Falha ao eliminar a pasta da captura: %@. O registo da base de dados foi mantido para evitar a ressurreição de dados. Elimine a pasta manualmente e tente novamente.', 'Не удалось удалить папку скриншота: %@. Запись в базе данных сохранена для предотвращения восстановления данных. Удалите папку вручную и повторите.', 'فشل حذف مجلد لقطة الشاشة: %@. تم الاحتفاظ بسجل قاعدة البيانات لمنع إحياء البيانات. احذف المجلد يدويًا وأعد المحاولة.', 'स्क्रीनशॉट फ़ोल्डर हटाने में विफल: %@. डेटा पुनरुत्थान रोकने के लिए डेटाबेस रिकॉर्ड बनाए रखा गया। फ़ोल्डर मैन्युअल रूप से हटाकर पुनः प्रयास करें।', 'ลบโฟลเดอร์ภาพหน้าจอไม่สำเร็จ: %@ มีการเก็บรrecord ฐานข้อมูลไว้เพื่อป้องกันข้อมูลฟื้นคืน โปรดลบโฟลเดอร์ด้วยตนเองแล้วลองอีกครั้ง', 'Xóa thư mục ảnh chụp màn hình thất bại: %@. Bản ghi cơ sở dữ liệu được giữ lại để tránh dữ liệu hồi sinh. Hãy xóa thư mục thủ công rồi thử lại.', 'Gagal menghapus folder tangkapan layar: %@. Catatan database tetap disimpan untuk mencegah kebangkitan data. Hapus folder secara manual lalu coba lagi.', 'Ekran görüntüsü klasörü silinemedi: %@. Veri canlanmasını önlemek için veritabanı kaydı tutuldu. Klasörü elle silin ve tekrar deneyin.', 'Verwijderen van schermafbeeldingsmap mislukt: %@. De databaserigi is bewaard om data-herleving te voorkomen. Verwijder de map handmatig en probeer opnieuw.', 'Nie udało się usunąć folderu zrzutu ekranu: %@. Rekord bazy danych zachowano, aby zapobiec odrodzeniu danych. Usuń folder ręcznie i spróbuj ponownie.', 'Не вдалося видалити папку знімка екрана: %@. Запис у базі даних збережено для запобігання «воскресінню» даних. Видаліть папку вручну і повторіть спробу.', 'Kunde inte ta bort skärmdumpsmappen: %@. Databasposten behölls för att förhindra dataåterupplivning. Ta bort mappen manuellt och försök igen.'])
add('部分待办写入失败：成功 %lld 个，失败 %lld 个', ['部分待辦寫入失敗：成功 %lld 個，失敗 %lld 個', 'Some todos failed to write: %lld succeeded, %lld failed', '一部の書き込みに失敗：成功 %lld 件、失敗 %lld 件', '일부 할 일 쓰기 실패: 성공 %lld개, 실패 %lld개', 'Certaines tâches n’ont pas été écrites : %lld réussies, %lld échouées', 'Einige Aufgaben konnten nicht geschrieben werden: %lld erfolgreich, %lld fehlgeschlagen', 'Algunas tareas fallaron al escribir: %lld exitosas, %lld fallidas', 'Alcune attività non sono state scritte: %lld riuscite, %lld non riuscite', 'Algumas tarefas falharam ao escrever: %lld bem-sucedidas, %lld falhadas', 'Некоторые задачи не записаны: успешно %lld, не удалось %lld', 'فشل كتابة بعض المهام: نجح %lld، فشل %lld', 'कुछ कार्य लिखने में विफल: %lld सफल, %lld असफल', 'เขียนสิ่งที่ต้องทำบางรายการไม่สำเร็จ: สำเร็จ %lld รายการ ล้มเหลว %lld รายการ', 'Ghi một số việc cần làm thất bại: thành công %lld, thất bại %lld', 'Beberapa tugas gagal ditulis: %lld berhasil, %lld gagal', 'Bazı görevler yazılamadı: %lld başarılı, %lld başarısız', 'Sommige taken konden niet worden weggeschreven: %lld geslaagd, %lld mislukt', 'Nie udało się zapisać niektórych zadań: %lld zakończonych, %lld niepowodzeń', 'Не вдалося записати деякі завдання: успішно %lld, невдало %lld', 'Vissa uppgifter kunde inte skrivas: %lld lyckades, %lld misslyckades'])

# BATCH_APPEND_MARKER

with open(CATALOG) as f:
    data = json.load(f)

added, skipped = 0, 0
for key, vals in T.items():
    if key in data['strings']:
        skipped += 1
        continue
    data['strings'][key] = {
        'localizations': {
            lang: {'stringUnit': {'state': 'translated', 'value': v}}
            for lang, v in zip(LANGS, vals)
        }
    }
    added += 1

with open(CATALOG, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write('\n')

print(f'added: {added}, skipped(existing): {skipped}, total keys: {len(data["strings"])}')
