#!/usr/bin/env python3
# 截图功能第三批本地化键（设置页/详情页/通用）：20 种语言
import json

CATALOG = 'Memonta/Resources/Localizable.xcstrings'
LANGS = ['zh-Hant', 'en', 'ja', 'ko', 'fr', 'de', 'es', 'it', 'pt', 'ru',
         'ar', 'hi', 'th', 'vi', 'id', 'tr', 'nl', 'pl', 'uk', 'sv']

T = {}


def add(key, vals):
    assert len(vals) == 20, key
    T[key] = vals

add('全局热键', ['全域熱鍵', 'Global Hotkey', 'グローバルホットキー', '전역 단축키', 'Raccourci global', 'Globaler Hotkey', 'Atajo global', 'Scorciatoia globale', 'Atalho global', 'Глобальная горячая клавиша', 'مفتاح اختصار عام', 'ग्लोबल हॉटकी', 'ปุ่มลัดสากล', 'Phím tắt toàn cục', 'Hotkey global', 'Genel Kısayol', 'Algemene sneltoets', 'Globalny skrót', 'Глобальна гаряча клавіша', 'Globalt kortkommando'])
add('截图热键', ['截圖熱鍵', 'Screenshot Hotkey', 'スクリーンショットのホットキー', '스크린샷 단축키', 'Raccourci de capture', 'Screenshot-Hotkey', 'Atajo de captura', 'Scorciatoia screenshot', 'Atalho de captura', 'Горячая клавиша скриншота', 'مفتاح اختصار لقطة الشاشة', 'स्क्रीनशॉट हॉटकी', 'ปุ่มลัดภาพหน้าจอ', 'Phím tắt chụp màn hình', 'Hotkey tangkapan layar', 'Ekran Görüntüsü Kısayolu', 'Screenshot-sneltoets', 'Skrót zrzutu ekranu', 'Гаряча клавіша знімка', 'Kortkommando för skärmdump'])
add('应用未激活时也可触发（区域截图）', ['應用程式未啟用時也可觸發（區域截圖）', 'Works even when the app is inactive (region capture)', 'アプリ非アクティブ時でも起動できます（領域切り取り）', '앱이 비활성 상태여도 실행 가능(영역 캡처)', 'Fonctionne même quand l’app est inactive (capture de zone)', 'Funktioniert auch bei inaktiver App (Bereichsaufnahme)', 'Funciona incluso con la app inactiva (captura de zona)', 'Funziona anche con l’app inattiva (cattura area)', 'Funciona mesmo com a app inativa (captura de região)', 'Работает, даже когда приложение неактивно (захват области)', 'يعمل حتى عندما يكون التطبيق غير نشط (التقاط المنطقة)', 'ऐप निष्क्रिय होने पर भी काम करता है (क्षेत्र कैप्चर)', 'ทำงานแม้แอปไม่ได้ใช้งานอยู่ (จับภาพบริเวณ)', 'Hoạt động cả khi ứng dụng không kích hoạt (chụp vùng)', 'Berfungsi meski aplikasi tidak aktif (tangkapan area)', 'Uygulama etkin olmasa bile çalışır (bölge yakalama)', 'Werkt ook als de app inactief is (gebiedsvastlegging)', 'Działa, nawet gdy aplikacja jest nieaktywna (zrzut obszaru)', 'Працює, навіть коли застосунок неактивний (захоплення області)', 'Fungerar även när appen är inaktiv (områdesbild)'])
add('修改热键', ['修改熱鍵', 'Change Hotkey', 'ホットキーを変更', '단축키 변경', 'Modifier le raccourci', 'Hotkey ändern', 'Cambiar atajo', 'Modifica scorciatoia', 'Alterar atalho', 'Изменить горячую клавишу', 'تغيير مفتاح الاختصار', 'हॉटकी बदलें', 'เปลี่ยนปุ่มลัด', 'Đổi phím tắt', 'Ubah hotkey', 'Kısayolu Değiştir', 'Sneltoets wijzigen', 'Zmień skrót', 'Змінити гарячу клавішу', 'Ändra kortkommando'])
add('恢复默认', ['恢復預設', 'Reset to Default', 'デフォルトに戻す', '기본값으로 복원', 'Rétablir par défaut', 'Auf Standard zurücksetzen', 'Restablecer', 'Ripristina predefinito', 'Restaurar predefinição', 'Сбросить', 'استعادة الافتراضي', 'डिफ़ॉल्ट पर लौटाएँ', 'กลับเป็นค่าเริ่มต้น', 'Khôi phục mặc định', 'Kembalikan ke bawaan', 'Varsayılana Dön', 'Standaard herstellen', 'Przywróć domyślne', 'Відновити типове', 'Återställ standard'])
add('热键注册失败', ['熱鍵註冊失敗', 'Hotkey Registration Failed', 'ホットキーの登録に失敗', '단축키 등록 실패', 'Échec d’enregistrement du raccourci', 'Hotkey-Registrierung fehlgeschlagen', 'Fallo al registrar el atajo', 'Registrazione scorciatoia non riuscita', 'Falha ao registar o atalho', 'Не удалось зарегистрировать горячую клавишу', 'فشل تسجيل مفتاح الاختصار', 'हॉटकी पंजीकरण विफल', 'ลงทะเบียนปุ่มลัดไม่สำเร็จ', 'Đăng ký phím tắt thất bại', 'Gagal mendaftarkan hotkey', 'Kısayol Kaydı Başarısız', 'Registratie van sneltoets mislukt', 'Nie udało się zarejestrować skrótu', 'Не вдалося зареєструвати гарячу клавішу', 'Registrering av kortkommando misslyckades'])
add('好', ['好', 'OK', 'OK', '확인', 'OK', 'OK', 'OK', 'OK', 'OK', 'ОК', 'حسنًا', 'ठीक है', 'ตกลง', 'OK', 'OK', 'Tamam', 'OK', 'OK', 'Гаразд', 'OK'])
add('请按下新的组合键（需包含 ⌘/⌥/⌃ 中至少一个修饰键），按 Esc 取消', ['請按下新的組合鍵（需包含 ⌘/⌥/⌃ 中至少一個修飾鍵），按 Esc 取消', 'Press a new key combination (must include at least one modifier: ⌘/⌥/⌃); Esc to cancel', '新しいキーの組み合わせを押してください（⌘/⌥/⌃のうち少なくとも1つの装飾キーが必要）。Escでキャンセル', '새 조합 키를 누르세요(⌘/⌥/⌃ 중 하나 이상의 보조 키 필요). Esc로 취소', 'Appuyez sur une nouvelle combinaison (au moins un modificateur requis : ⌘/⌥/⌃) ; Échap pour annuler', 'Drücken Sie eine neue Tastenkombination (mindestens ein Modifikator erforderlich: ⌘/⌥/⌃); Esc zum Abbrechen', 'Pulse una nueva combinación (se requiere al menos un modificador: ⌘/⌥/⌃); Esc para cancelar', 'Premi una nuova combinazione (richiesto almeno un modificatore: ⌘/⌥/⌃); Esc per annullare', 'Prima uma nova combinação (obrigatório pelo menos um modificador: ⌘/⌥/⌃); Esc para cancelar', 'Нажмите новую комбинацию (нужен хотя бы один модификатор: ⌘/⌥/⌃); Esc — отмена', 'اضغط تركيبة مفاتيح جديدة (يلزم معدِّل واحد على الأقل: ⌘/⌥/⌃)؛ Esc للإلغاء', 'नया कुंजी संयोजन दबाएँ (कम से कम एक मॉडिफ़ायर आवश्यक: ⌘/⌥/⌃); रद्द करने के लिए Esc', 'กดชุดปุ่มใหม่ (ต้องมีปุ่มแก้ไขอย่างน้อยหนึ่งปุ่ม: ⌘/⌥/⌃) กด Esc เพื่อยกเลิก', 'Nhấn tổ hợp phím mới (cần ít nhất một phím bổ trợ: ⌘/⌥/⌃); nhấn Esc để hủy', 'Tekan kombinasi tombol baru (wajib minimal satu pengubah: ⌘/⌥/⌃); Esc untuk batal', 'Yeni bir tuş birleşimine basın (en az bir değiştirici gerekli: ⌘/⌥/⌃); iptal için Esc', 'Druk op een nieuwe toetscombinatie (minstens één modificatortoets vereist: ⌘/⌥/⌃); Esc om te annuleren', 'Naciśnij nową kombinację klawiszy (wymagany co najmniej jeden modyfikator: ⌘/⌥/⌃); Esc anuluje', 'Натисніть нову комбінацію (потрібен хоча б один модифікатор: ⌘/⌥/⌃); Esc — скасувати', 'Tryck en ny tangentkombination (minst en modifierartangent krävs: ⌘/⌥/⌃); Esc avbryter'])
add('该组合键可能已被其他应用占用，请换一个组合键。', ['該組合鍵可能已被其他應用程式佔用，請換一個組合鍵。', 'This key combination may already be in use by another app. Please choose another one.', 'このキーの組み合わせは他のアプリで使用中の可能性があります。別の組み合わせを選択してください。', '이 조합 키는 다른 앱에서 이미 사용 중일 수 있습니다. 다른 조합을 선택하세요.', 'Cette combinaison est peut-être déjà utilisée par une autre app. Choisissez-en une autre.', 'Diese Tastenkombination wird möglicherweise bereits von einer anderen App verwendet. Bitte eine andere wählen.', 'Es posible que otra app ya use esta combinación. Elija otra.', 'Questa combinazione potrebbe essere già in uso da un’altra app. Scegline un’altra.', 'Esta combinação pode já estar a ser usada por outra app. Escolha outra.', 'Эта комбинация может быть уже занята другим приложением. Выберите другую.', 'قد يكون تركيب المفاتيح هذا مستخدمًا بالفعل من تطبيق آخر. اختر تركيبة أخرى.', 'यह कुंजी संयोजन किसी अन्य ऐप द्वारा पहले से उपयोग में हो सकता है। कृपया दूसरा चुनें।', 'ชุดปุ่มนี้อาจถูกแอปอื่นใช้อยู่แล้ว โปรดเลือกชุดอื่น', 'Tổ hợp phím này có thể đã bị ứng dụng khác chiếm dụng. Hãy chọn tổ hợp khác.', 'Kombinasi tombol ini mungkin sudah dipakai aplikasi lain. Silakan pilih yang lain.', 'Bu tuş birleşimi başka bir uygulama tarafından kullanılıyor olabilir. Lütfen başka bir tane seçin.', 'Deze toetscombinatie wordt mogelijk al door een andere app gebruikt. Kies een andere.', 'Ta kombinacja klawiszy może być już używana przez inną aplikację. Wybierz inną.', 'Ця комбінація може вже використовуватися іншим застосунком. Виберіть іншу.', 'Denna tangentkombination används kanske redan av en annan app. Välj en annan.'])
add('屏幕录制权限', ['螢幕錄製權限', 'Screen Recording Permission', '画面収録権限', '화면 녹화 권한', 'Autorisation d’enregistrement de l’écran', 'Berechtigung für Bildschirmaufnahme', 'Permiso de grabación de pantalla', 'Autorizzazione registrazione schermo', 'Permissão de gravação de ecrã', 'Разрешение на запись экрана', 'إذن تسجيل الشاشة', 'स्क्रीन रिकॉर्डिंग अनुमति', 'สิทธิ์การบันทึกหน้าจอ', 'Quyền ghi màn hình', 'Izin perekaman layar', 'Ekran Kaydı İzni', 'Toestemming voor schermopname', 'Uprawnienie do nagrywania ekranu', 'Дозвіл на запис екрана', 'Behörighet för skärminspelning'])
add('已授权，可以正常截图', ['已授權，可以正常截圖', 'Granted; screenshots will work normally', '許可済みのため、通常どおりスクリーンショットを撮影できます', '승인됨, 정상적으로 스크린샷을 촬영할 수 있습니다', 'Accordée ; les captures fonctionneront normalement', 'Erteilt; Screenshots funktionieren normal', 'Concedido; las capturas funcionarán con normalidad', 'Concessa; gli screenshot funzioneranno normalmente', 'Concedida; as capturas funcionarão normalmente', 'Разрешение выдано; скриншоты будут работать штатно', 'ممنوح؛ ستعمل لقطات الشاشة بشكل طبيعي', 'अनुमति दी गई; स्क्रीनशॉट सामान्य रूप से काम करेंगे', 'ได้รับอนุญาตแล้ว จับภาพหน้าจอได้ตามปกติ', 'Đã cấp; ảnh chụp sẽ hoạt động bình thường', 'Diberikan; tangkapan layar akan berfungsi normal', 'Verildi; ekran görüntüleri normal şekilde çalışacak', 'Verleend; schermafbeeldingen werken normaal', 'Przyznane; zrzuty ekranu będą działać normalnie', 'Надано; знімки екрана працюватимуть нормально', 'Beviljad; skärmdumpar fungerar normalt'])
add('未授权，首次截图时系统会弹窗请求授权', ['未授權，首次截圖時系統會彈窗請求授權', 'Not granted; the system will prompt for permission on first capture', '未許可。初回のスクリーンショット時にシステムが許可を求めます', '승인되지 않음. 첫 스크린샷 시 시스템이 권한을 요청합니다', 'Non accordée ; le système demandera l’autorisation à la première capture', 'Nicht erteilt; das System fragt bei der ersten Aufnahme nach der Berechtigung', 'Sin conceder; el sistema pedirá permiso en la primera captura', 'Non concessa; il sistema chiederà l’autorizzazione alla prima cattura', 'Não concedida; o sistema pedirá permissão na primeira captura', 'Не выдано; при первом скриншоте система запросит разрешение', 'غير ممنوح؛ سيطلب النظام الإذن عند أول لقطة شاشة', 'अनुमति नहीं दी गई; पहली कैप्चर पर सिस्टम अनुमति मांगेगा', 'ยังไม่ได้รับอนุญาต ระบบจะขอสิทธิ์เมื่อจับภาพครั้งแรก', 'Chưa cấp; hệ thống sẽ yêu cầu quyền ở lần chụp đầu tiên', 'Belum diberikan; sistem akan meminta izin saat tangkapan pertama', 'Verilmedi; sistem ilk yakalamada izin isteyecek', 'Niet verleend; het systeem vraagt bij de eerste vastlegging om toestemming', 'Nie przyznane; przy pierwszym zrzucie system poprosi o uprawnienie', 'Не надано; під час першого знімка система запитає дозвіл', 'Inte beviljad; systemet frågar efter behörighet vid första fångsten'])
add('截图功能仅支持 macOS。', ['截圖功能僅支援 macOS。', 'The screenshot feature is macOS only.', 'スクリーンショット機能はmacOS専用です。', '스크린샷 기능은 macOS 전용입니다.', 'La fonction de capture est réservée à macOS.', 'Die Screenshot-Funktion ist nur für macOS verfügbar.', 'La función de captura solo está disponible en macOS.', 'La funzione screenshot è disponibile solo su macOS.', 'A função de captura está disponível apenas no macOS.', 'Функция скриншота доступна только на macOS.', 'ميزة لقطة الشاشة متاحة على macOS فقط.', 'स्क्रीनशॉट सुविधा केवल macOS के लिए है।', 'คุณสมบัติภาพหน้าจอรองรับเฉพาะ macOS', 'Tính năng chụp màn hình chỉ có trên macOS.', 'Fitur tangkapan layar hanya tersedia di macOS.', 'Ekran görüntüsü özelliği yalnızca macOS içindir.', 'De screenshotfunctie is alleen beschikbaar op macOS.', 'Funkcja zrzutów ekranu jest dostępna tylko na macOS.', 'Функція знімків екрана доступна лише на macOS.', 'Skärmdumpsfunktionen finns endast på macOS.'])
add('确认删除截图？', ['確認刪除截圖？', 'Delete this screenshot?', 'スクリーンショットを削除しますか？', '스크린샷을 삭제할까요?', 'Supprimer cette capture ?', 'Diesen Screenshot löschen?', '¿Eliminar esta captura?', 'Eliminare questo screenshot?', 'Eliminar esta captura?', 'Удалить этот скриншот?', 'حذف لقطة الشاشة هذه؟', 'यह स्क्रीनशॉट हटाएँ?', 'ลบภาพหน้าจอนี้หรือไม่?', 'Xóa ảnh chụp màn hình này?', 'Hapus tangkapan layar ini?', 'Bu ekran görüntüsü silinsin mi?', 'Deze schermafbeelding verwijderen?', 'Usunąć ten zrzut ekranu?', 'Видалити цей знімок екрана?', 'Ta bort den här skärmdumpen?'])
add('确认删除选中的截图？', ['確認刪除選中的截圖？', 'Delete the selected screenshots?', '選択したスクリーンショットを削除しますか？', '선택한 스크린샷을 삭제할까요?', 'Supprimer les captures sélectionnées ?', 'Ausgewählte Screenshots löschen?', '¿Eliminar las capturas seleccionadas?', 'Eliminare gli screenshot selezionati?', 'Eliminar as capturas selecionadas?', 'Удалить выбранные скриншоты?', 'حذف لقطات الشاشة المحددة؟', 'चयनित स्क्रीनशॉट हटाएँ?', 'ลบภาพหน้าจอที่เลือกหรือไม่?', 'Xóa các ảnh chụp đã chọn?', 'Hapus tangkapan layar yang dipilih?', 'Seçili ekran görüntüleri silinsin mi?', 'Geselecteerde schermafbeeldingen verwijderen?', 'Usunąć zaznaczone zrzuty ekranu?', 'Видалити вибрані знімки екрана?', 'Ta bort valda skärmdumpar?'])
add('选中的截图及其文件将一并删除，删除后无法恢复。', ['選中的截圖及其檔案將一併刪除，刪除後無法復原。', 'The selected screenshots and their files will be deleted and cannot be recovered.', '選択したスクリーンショットとそのファイルは削除され、復元できません。', '선택한 스크린샷과 해당 파일이 함께 삭제되며 복원할 수 없습니다.', 'Les captures sélectionnées et leurs fichiers seront supprimés, sans possibilité de récupération.', 'Die ausgewählten Screenshots und ihre Dateien werden gelöscht und können nicht wiederhergestellt werden.', 'Las capturas seleccionadas y sus archivos se eliminarán y no se podrán recuperar.', 'Gli screenshot selezionati e i relativi file saranno eliminati e non recuperabili.', 'As capturas selecionadas e os respetivos ficheiros serão eliminados e não podem ser recuperados.', 'Выбранные скриншоты и их файлы будут удалены без возможности восстановления.', 'ستُحذف لقطات الشاشة المحددة وملفاتها نهائيًا ولا يمكن استعادتها.', 'चयनित स्क्रीनशॉट और उनकी फ़ाइलें हटा दी जाएँगी और उन्हें पुनर्प्राप्त नहीं किया जा सकता।', 'ภาพหน้าจอที่เลือกและไฟล์ประกอบจะถูกลบและกู้คืนไม่ได้', 'Các ảnh chụp đã chọn và tệp của chúng sẽ bị xóa và không thể khôi phục.', 'Tangkapan layar yang dipilih beserta filenya akan dihapus dan tidak dapat dipulihkan.', 'Seçili ekran görüntüleri ve dosyaları silinecek ve geri alınamaz.', 'De geselecteerde schermafbeeldingen en hun bestanden worden verwijderd en kunnen niet worden hersteld.', 'Zaznaczone zrzuty ekranu i ich pliki zostaną usunięte i nie będzie można ich przywrócić.', 'Вибрані знімки екрана та їхні файли буде видалено без можливості відновлення.', 'De valda skärmdumparna och deras filer tas bort och kan inte återställas.'])
add('工具栏「截图」按钮、菜单栏「截图」子菜单或全局热键均可启动', ['工具列「截圖」按鈕、選單列「截圖」子選單或全域熱鍵均可啟動', 'Start from the toolbar “Screenshot” button, the menu bar “Screenshot” submenu, or the global hotkey', 'ツールバーの「スクリーンショット」ボタン、メニューバーの「スクリーンショット」サブメニュー、グローバルホットキーのいずれでも起動可能', '도구 모음의 "스크린샷" 버튼, 메뉴 막대의 "스크린샷" 하위 메뉴, 전역 단축키 모두에서 시작 가능', 'Démarrez depuis le bouton « Capture » de la barre d’outils, le sous-menu « Capture » de la barre de menus ou le raccourci global', 'Start über die Schaltfläche „Screenshot“ der Symbolleiste, das Untermenü „Screenshot“ der Menüleiste oder den globalen Hotkey', 'Puede iniciarse desde el botón «Captura» de la barra de herramientas, el submenú «Captura» de la barra de menús o el atajo global', 'Avviabile dal pulsante “Screenshot” della barra strumenti, dal sottomenu “Screenshot” della barra dei menu o dalla scorciatoia globale', 'Iniciável pelo botão “Captura” da barra de ferramentas, pelo submenu “Captura” da barra de menus ou pelo atalho global', 'Запускается кнопкой «Скриншот» на панели инструментов, подменю «Скриншот» в строке меню или глобальной горячей клавишей', 'يمكن البدء من زر «لقطة الشاشة» في شريط الأدوات، أو القائمة الفرعية «لقطة الشاشة» في شريط القوائم، أو مفتاح الاختصار العام', 'टूलबार के "स्क्रीनशॉट" बटन, मेनू बार के "स्क्रीनशॉट" सबमेनू या ग्लोबल हॉटकी से शुरू करें', 'เริ่มได้จากปุ่ม "ภาพหน้าจอ" ในแถบเครื่องมือ เมนูย่อย "ภาพหน้าจอ" ในแถบเมนู หรือปุ่มลัดสากล', 'Có thể bắt đầu từ nút "Ảnh chụp" trên thanh công cụ, menu con "Ảnh chụp" trên thanh menu hoặc phím tắt toàn cục', 'Dapat dimulai dari tombol "Tangkapan" di bilah alat, submenu "Tangkapan" di bilah menu, atau hotkey global', 'Araç çubuğundaki "Ekran Görüntüsü" düğmesi, menü çubuğundaki "Ekran Görüntüsü" alt menüsü veya genel kısayoldan başlatılabilir', 'Te starten via de knop „Schermafbeelding” in de werkbalk, het submenu „Schermafbeelding” in de menubalk of de algemene sneltoets', 'Można uruchomić z przycisku „Zrzut ekranu” na pasku narzędzi, podmenu „Zrzut ekranu” w pasku menu lub globalnego skrótu', 'Можна запустити з кнопки «Знімок екрана» на панелі інструментів, підменю «Знімок екрана» в рядку меню або глобальної гарячої клавіші', 'Kan startas från knappen „Skärmdump” i verktygsfältet, undermenyn „Skärmdump” i menyraden eller det globala kortkommandot'])
add('框选区域后可标注：矩形 / 椭圆 / 箭头 / 画笔 / 文字 / 马赛克，支持撤销', ['框選區域後可標註：矩形 / 橢圓 / 箭頭 / 畫筆 / 文字 / 馬賽克，支援撤銷', 'After selecting a region, annotate with rectangle / ellipse / arrow / pen / text / mosaic; undo supported', '領域選択後に注釈可能：四角形／楕円／矢印／ペン／テキスト／モザイク、取り消し対応', '영역 선택 후 주석 가능: 사각형 / 타원 / 화살표 / 펜 / 텍스트 / 모자이크, 실행 취소 지원', 'Après sélection de zone, annotez : rectangle / ellipse / flèche / stylet / texte / mosaïque ; annuler pris en charge', 'Nach der Bereichsauswahl annotieren: Rechteck / Ellipse / Pfeil / Stift / Text / Mosaik; Widerrufen unterstützt', 'Tras seleccionar una zona, anote: rectángulo / elipse / flecha / lápiz / texto / mosaico; deshacer soportado', 'Dopo la selezione dell’area, annota: rettangolo / ellisse / freccia / penna / testo / mosaico; annulla supportato', 'Após selecionar a região, anote: retângulo / elipse / seta / caneta / texto / mosaico; desfazer suportado', 'После выделения области аннотируйте: прямоугольник / овал / стрелка / перо / текст / мозаика; поддерживается отмена', 'بعد تحديد المنطقة، علّم: مستطيل / قطع ناقص / سهم / قلم / نص / موزاييك؛ مع دعم التراجع', 'क्षेत्र चयन के बाद एनोटेट करें: आयत / दीर्घवृत्त / तीर / पेन / टेक्स्ट / मोज़ेक; पूर्ववत समर्थित', 'หลังลากเลือกบริเวณแล้วใส่คำอธิบายได้: สี่เหลี่ยม / วงรี / ลูกศร / ปากกา / ข้อความ / โมเสก รองรับเลิกทำ', 'Sau khi kéo chọn vùng, chú thích: hình chữ nhật / elip / mũi tên / bút / văn bản / khảm; hỗ trợ hoàn tác', 'Setelah menyeleksi area, beri anotasi: persegi panjang / elips / panah / pena / teks / mozaik; mendukung urungkan', 'Bölge seçtikten sonra açıklama ekleyin: dikdörtgen / elips / ok / kalem / metin / mozaik; geri alma desteklenir', 'Na het selecteren van een gebied: rechthoek / ellips / pijl / pen / tekst / mozaïek; ongedaan maken ondersteund', 'Po zaznaczeniu obszaru dodaj adnotacje: prostokąt / elipsa / strzałka / pióro / tekst / mozaika; obsługa cofania', 'Після виділення області анотуйте: прямокутник / овал / стрілка / перо / текст / мозаїка; підтримується скасування', 'Efter områdesmarkering: rektangel / ellips / pil / penna / text / mosaik; ångra stöds'])
add('悬浮层工具条可复制到剪贴板、保存归档或取消', ['懸浮層工具列可複製到剪貼簿、儲存歸檔或取消', 'The floating toolbar can copy to clipboard, save to the archive, or cancel', 'フローティングツールバーでクリップボードにコピー、アーカイブに保存、またはキャンセル', '플로팅 도구 모음에서 클립보드로 복사, 보관함에 저장 또는 취소 가능', 'La barre d’outils flottante permet de copier dans le presse-papiers, d’enregistrer dans l’archive ou d’annuler', 'Die schwebende Symbolleiste kann in die Zwischenablage kopieren, im Archiv speichern oder abbrechen', 'La barra de herramientas flotante permite copiar al portapapeles, guardar en el archivo o cancelar', 'La barra strumenti flottante consente di copiare negli appunti, salvare nell’archivio o annullare', 'A barra de ferramentas flutuante permite copiar para a área de transferência, guardar no arquivo ou cancelar', 'Плавающая панель инструментов может копировать в буфер обмена, сохранять в архив или отменять', 'يمكن لشريط الأدوات العائم النسخ إلى الحافظة أو الحفظ في الأرشيف أو الإلغاء', 'फ़्लोटिंग टूलबार क्लिपबोर्ड पर कॉपी, संग्रह में सहेजने या रद्द कर सकता है', 'แถบเครื่องมือลอยใช้คัดลอกไปคลิปบอร์ด บันทึกลงที่เก็บ หรือยกเลิกได้', 'Thanh công cụ nổi có thể sao chép vào bảng tạm, lưu vào kho lưu trữ hoặc hủy', 'Bilah alat mengambang dapat menyalin ke papan klip, menyimpan ke arsip, atau membatalkan', 'Yüzen araç çubuğu panoya kopyalayabilir, arşive kaydedebilir veya iptal edebilir', 'De zwevende werkbalk kan naar het klembord kopiëren, in het archief opslaan of annuleren', 'Pływający pasek narzędzi może kopiować do schowka, zapisywać w archiwum lub anulować', 'Плаваюча панель інструментів може копіювати в буфер обміну, зберігати в архіві або скасовувати', 'Det flytande verktygsfältet kan kopiera till urklipp, spara i arkivet eller avbryta'])
add('归档截图自动本地 OCR 识别文字，可送多模态 LLM 生成总结与待办', ['歸檔截圖自動本地 OCR 識別文字，可送多模態 LLM 生成總結與待辦', 'Archived screenshots are OCR’d locally; send them to multimodal LLMs for summaries and todos', 'アーカイブされたスクリーンショットはローカルで自動OCR認識され、マルチモーダルLLMで要約とタスクを生成可能', '보관된 스크린샷은 로컬에서 자동 OCR되며, 멀티모달 LLM으로 요약과 할 일 생성 가능', 'Les captures archivées sont OCRisées localement ; envoyez-les à des LLM multimodaux pour résumés et tâches', 'Archivierte Screenshots werden lokal per OCR erkannt; senden Sie sie an multimodale LLMs für Zusammenfassungen und Aufgaben', 'Las capturas archivadas se procesan con OCR local; envíelas a LLM multimodales para resúmenes y tareas', 'Gli screenshot archiviati vengono riconosciuti localmente via OCR; inviali a LLM multimodali per riepiloghi e attività', 'As capturas arquivadas são processadas por OCR local; envie-as a LLMs multimodais para resumos e tarefas', 'Архивированные скриншоты распознаются локально через OCR; отправляйте их мультимодальным LLM для сводок и задач', 'تُعرف لقطات الشاشة المؤرشفة محليًا عبر OCR؛ أرسلها إلى نماذج متعددة الوسائط لتوليد الملخصات والمهام', 'संग्रहीत स्क्रीनशॉट स्थानीय रूप से OCR होते हैं; सारांश और कार्य के लिए उन्हें मल्टीमॉडल LLM को भेजें', 'ภาพหน้าจอที่จัดเก็บจะ OCR ในเครื่องอัตโนมัติ ส่งให้มัลติโมดัล LLM เพื่อสร้างสรุปและสิ่งที่ต้องทำได้', 'Ảnh chụp đã lưu trữ được OCR cục bộ; gửi chúng tới LLM đa phương thức để tạo tóm tắt và việc cần làm', 'Tangkapan layar yang diarsipkan di-OCR secara lokal; kirim ke LLM multimodal untuk ringkasan dan tugas', 'Arşivlenen ekran görüntüleri yerel olarak OCR yapılır; özet ve görevler için çok modlu LLM’lere gönderin', 'Gearchiveerde schermafbeeldingen worden lokaal ge-OCR’d; stuur ze naar multimodale LLM’s voor samenvattingen en taken', 'Zarchiwizowane zrzuty ekranu są rozpoznawane lokalnie przez OCR; wyślij je do multimodalnego LLM po podsumowania i zadania', 'Заархівовані знімки екрана розпізнаються локально через OCR; надсилайте їх мультимодальним LLM для зведень і завдань', 'Arkiverade skärmdumpar OCR-läses lokalt; skicka dem till multimodala LLM:er för sammanfattningar och uppgifter'])
add('截图保存为 PNG 原图（不加密），存储在文稿/Memonta 文件夹按月份归档', ['截圖儲存為 PNG 原圖（不加密），儲存在文稿/Memonta 資料夾按月份歸檔', 'Screenshots are saved as original PNGs (unencrypted), stored by month in the Documents/Memonta folder', 'スクリーンショットはPNG原画（暗号化なし）として保存され、書類/Memontaフォルダで月別に管理', '스크린샷은 PNG 원본(암호화 없음)으로 저장되며, 문서/Memonta 폴더에 월별로 보관', 'Les captures sont enregistrées en PNG d’origine (non chiffrées), stockées par mois dans le dossier Documents/Memonta', 'Screenshots werden als originale PNG-Dateien (unverschlüsselt) gespeichert, monatlich im Ordner „Dokumente/Memonta“ abgelegt', 'Las capturas se guardan como PNG originales (sin cifrar), almacenadas por mes en la carpeta Documentos/Memonta', 'Gli screenshot sono salvati come PNG originali (non cifrati), archiviati per mese nella cartella Documenti/Memonta', 'As capturas são guardadas como PNG originais (sem encriptação), armazenadas por mês na pasta Documentos/Memonta', 'Скриншоты сохраняются как оригинальные PNG (без шифрования) и хранятся по месяцам в папке «Документы/Memonta»', 'تُحفظ لقطات الشاشة كملفات PNG أصلية (بدون تشفير)، وتُخزن شهريًا في مجلد المستندات/Memonta', 'स्क्रीनशॉट मूल PNG के रूप में सहेजे जाते हैं (अनएन्क्रिप्टेड), दस्तावेज़/Memonta फ़ोल्डर में मासिक रूप से संग्रहीत', 'ภาพหน้าจอบันทึกเป็น PNG ต้นฉบับ (ไม่เข้ารหัส) เก็บรายเดือนในโฟลเดอร์ เอกสาร/Memonta', 'Ảnh chụp lưu dạng PNG gốc (không mã hóa), lưu theo tháng trong thư mục Tài liệu/Memonta', 'Tangkapan layar disimpan sebagai PNG asli (tanpa enkripsi), disimpan per bulan di folder Dokumen/Memonta', 'Ekran görüntüleri özgün PNG olarak kaydedilir (şifresiz), Belgeler/Memonta klasöründe aylık saklanır', 'Schermafbeeldingen worden als originele PNG’s (onversleuteld) opgeslagen, maandelijks in de map Documenten/Memonta', 'Zrzuty ekranu są zapisywane jako oryginalne pliki PNG (bez szyfrowania), przechowywane co miesiąc w folderze Dokumenty/Memonta', 'Знімки екрана зберігаються як оригінальні PNG (без шифрування) і зберігаються щомісяця в папці Документи/Memonta', 'Skärmdumpar sparas som original-PNG (okrypterat), lagrade månadsvis i mappen Dokument/Memonta'])
add('使用本地 Vision OCR 识别截图中的文字（重新识别会覆盖已有结果）', ['使用本地 Vision OCR 識別截圖中的文字（重新識別會覆蓋已有結果）', 'Recognize text in the screenshot with local Vision OCR (re-running overwrites existing results)', 'ローカルのVision OCRでスクリーンショット内のテキストを認識（再実行すると既存の結果を上書き）', '로컬 Vision OCR로 스크린샷의 텍스트 인식(다시 실행하면 기존 결과 덮어씀)', 'Reconnaît le texte de la capture avec l’OCR Vision local (relancer écrase les résultats existants)', 'Erkennt Text im Screenshot mit lokalem Vision-OCR (erneutes Ausführen überschreibt vorhandene Ergebnisse)', 'Reconoce el texto de la captura con OCR Vision local (repetir sobrescribe los resultados existentes)', 'Riconosce il testo dello screenshot con Vision OCR locale (rieseguendo sovrascrive i risultati esistenti)', 'Reconhece o texto da captura com Vision OCR local (reexecutar substitui os resultados existentes)', 'Распознаёт текст на скриншоте локальным Vision OCR (повторный запуск перезапишет результаты)', 'يتعرّف على نص لقطة الشاشة عبر Vision OCR المحلي (إعادة التشغيل تستبدل النتائج الحالية)', 'लोकल Vision OCR से स्क्रीनशॉट का टेक्स्ट पहचानें (दोबारा चलाने पर मौजूदा परिणाम बदल जाएँगे)', 'รู้จำข้อความในภาพหน้าจอด้วย Vision OCR ในเครื่อง (รันซ้ำจะเขียนทับผลลัพธ์เดิม)', 'Nhận dạng văn bản trong ảnh chụp bằng Vision OCR cục bộ (chạy lại sẽ ghi đè kết quả hiện có)', 'Kenali teks dalam tangkapan layar dengan Vision OCR lokal (menjalankan ulang menimpa hasil yang ada)', 'Ekran görüntüsündeki metni yerel Vision OCR ile tanı (yeniden çalıştırmak mevcut sonuçların üzerine yazar)', 'Herkent tekst in de schermafbeelding met lokale Vision OCR (opnieuw uitvoeren overschrijft bestaande resultaten)', 'Rozpoznaje tekst na zrzucie lokalnym Vision OCR (ponowne uruchomienie nadpisze istniejące wyniki)', 'Розпізнає текст на знімку локальним Vision OCR (повторний запуск перезапише наявні результати)', 'Känner igen text i skärmdumpen med lokal Vision OCR (omkörning skriver över befintliga resultat)'])
add('从左侧列表选择录音、快捷笔记或截图，或点击工具栏按钮新建', ['從左側列表選擇錄音、快捷筆記或截圖，或點擊工具列按鈕新建', 'Select a recording, quick note, or screenshot from the list, or use the toolbar buttons to create one', '左のリストから録音、クイックノート、スクリーンショットを選択するか、ツールバーのボタンで新規作成', '왼쪽 목록에서 녹음, 빠른 노트 또는 스크린샷을 선택하거나 도구 모음 버튼으로 새로 만드세요', 'Sélectionnez un enregistrement, une note rapide ou une capture dans la liste, ou créez-en un via la barre d’outils', 'Wählen Sie links eine Aufnahme, Schnellnotiz oder einen Screenshot aus oder erstellen Sie über die Symbolleiste eine neue', 'Seleccione una grabación, nota rápida o captura en la lista, o cree una nueva con los botones de la barra', 'Seleziona a sinistra una registrazione, una nota rapida o uno screenshot, oppure creane uno con i pulsanti della barra strumenti', 'Selecione à esquerda uma gravação, nota rápida ou captura, ou crie uma com os botões da barra de ferramentas', 'Выберите слева запись, быструю заметку или скриншот либо создайте новую кнопками на панели', 'اختر من القائمة اليسرى تسجيلًا أو ملاحظة سريعة أو لقطة شاشة، أو أنشئ جديدًا عبر أزرار شريط الأدوات', 'बाईं सूची से रिकॉर्डिंग, क्विक नोट या स्क्रीनशॉट चुनें, या टूलबार बटन से नया बनाएँ', 'เลือกการบันทึกเสียง โน้ตด่วน หรือภาพหน้าจอจากรายการด้านซ้าย หรือสร้างใหม่ด้วยปุ่มในแถบเครื่องมือ', 'Chọn bản ghi, ghi chú nhanh hoặc ảnh chụp trong danh sách bên trái, hoặc tạo mới bằng nút trên thanh công cụ', 'Pilih rekaman, catatan cepat, atau tangkapan layar dari daftar kiri, atau buat baru lewat tombol bilah alat', 'Soldaki listeden bir kayıt, hızlı not veya ekran görüntüsü seçin ya da araç çubuğu düğmeleriyle yeni oluşturun', 'Kies links een opname, snelle notitie of schermafbeelding, of maak er een via de werkbalkknoppen', 'Wybierz z listy po lewej nagranie, szybką notatkę lub zrzut ekranu albo utwórz nowy przyciskiem na pasku', 'Виберіть ліворуч запис, швидку нотатку або знімок екрана, або створіть новий кнопкою на панелі', 'Välj en inspelning, snabbnotering eller skärmdump i listan till vänster, eller skapa en ny via verktygsfältet'])

with open(CATALOG) as f:
    data = json.load(f)

added, skipped = 0, 0
for key, vals in T.items():
    if key in data['strings']:
        skipped += 1
        continue
    data['strings'][key] = {
        'localizations': {
            lang: {'stringUnit': {'state': 'translated', 'value': v}}
            for lang, v in zip(LANGS, vals)
        }
    }
    added += 1

with open(CATALOG, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write('\n')

print(f'batch3 added: {added}, skipped(existing): {skipped}, total keys: {len(data["strings"])}')
